sceptre/connection_manager.py
sceptre/helpers.py

Renamed `anonymise_key` function in sceptre/helpers.py to `mask_key` as old name didn't properly describe the function.

Rename `anonymise_key` to `mask_key` 

---

tests/test_stack.py

Renamed the function in the Stack class to better represent its purpose.

Rename _get_role_details to _get_role_arn

---

docs/stack_config.rst
sceptre/stack.py
tests/test_stack.py

Add functionality to format a yaml list of parameters in a stack config as an AWS compatible comma separated list.

Sptr 4/parameter as lists

---

README.rst
requirements_dev.txt

This branch has no error when rendering README.rst with Pygments pack installed using the following commands:
`python setup.py check --restructuredtext -s `
and
`rst2html.py --strict README.rst`
This should fix PYPI README.rst rendering issues.

Fix PYPI README.rst rendering.

---

circle.yml

Changed the circleci deployment to only update docs at /docs/ with a new tag version and /dev/doc/ with the latest from master branch.

Update circle.yml to deploy docs based on tags

---

sceptre/helpers.py

The string check in `helpers.get_subclasses` was checking against `str`, meaning that passing a unicode string would fail.
The simple fix is to change the `isinstance` check to match against `basestring`.
**Note:** This isn't Python 3 compatible, but I didn't see any evidence that it's supported currently. Let me know if that's not the case.

Update string type check in get_subclasses to account for unicode

---

sceptre/config.py
tests/test_config.py

Rather than always loading custom resolvers and hooks from the current directory, they should instead be loaded from the sceptre dir along with config and templates.

Respect --dir when loading custom resolvers and hooks

---

Makefile
circle.yml
integration-tests/environment.py
integration-tests/steps/test_change_set.py
integration-tests/steps/test_continue_update_rollback.py
integration-tests/steps/test_create_stack.py
integration-tests/steps/test_delete_env.py
integration-tests/steps/test_delete_stack.py
integration-tests/steps/test_describe_env_and_describe_env_resources.py
integration-tests/steps/test_describe_stack_resources.py
integration-tests/steps/test_generate_template.py
integration-tests/steps/test_launch_env.py
integration-tests/steps/test_lock_unlock_stack.py
integration-tests/steps/test_update_stack.py
integration-tests/steps/test_validate_template.py

This PR makes use of CircleCI's parallel tests [feature](https://circleci.com/docs/1.0/parallel-manual-setup/#using-configuration-files-modifier) to speed up our integration tests. 
Circle's simple parallelism is file based. You supply a command and a list of files to run that command on. In our case, the command is `behave`, and the list of files is the result of the glob `integration-tests/features/*.feature`.
This command has to be run from the root directory, `sceptre/`. Previously, our integration tests were run from `sceptre/integration-tests`, where we store the config files and templates used by sceptre to run the tests. To get `behave` to run from the root dir, the integration tests have been modified so all sceptre commands are explicitly supplied with the sceptre directory to …

Parallelise circle

---

docs/stack_config.rst

- Add warning to not store passwords in stack config
- Switch quote marks to code block
- Remove warning that `file_path` resolver has been renamed to `file_contents` (it hasn't been called `file_path` since pre-1.0)

Add warning that users should not store passwords in stack config

---

AUTHORS.rst
docs/stack_config.rst
sceptre/exceptions.py
sceptre/hooks/asg_scaling_processes.py
tests/test_hooks/test_asg_scaling_processes.py

This sceptre hook can suspend/resume any autoscaling processes as they are defined in the AWS documentation:
http://docs.aws.amazon.com/autoscaling/latest/userguide/as-suspend-resume-processes.html

Add hook for ASG that supports all scaling processes

---

docs/stack_config.rst

This is how it works now. I don't see the point to have here the environment, but maybe it can be optional.

Fix dependency namming when using dependencies

---

circle.yml

Fix tag regex. `/v*/` (match 0 or more of the character 'v') doesn't actually match our tagging pattern e.g: `v1.1.1`. I've switched it to the regex Circle recommend in their [docs](https://circleci.com/docs/1.0/configuration/#tags).
Note we can't actually test this until we do a release, but I've been doing some testing of my own [here](https://github.com/jamesroutley/circleci-test), and I think it should work.

Fix circle ci tag regex

---

docs/stack_config.rst
sceptre/resolvers/project_variables.py

Added deprecation warning for the "project_variables" resolver as on Issue #116 and updated documentation accordingly.

Deprecate project_variables resolver #116

---

sceptre/helpers.py
tests/test_helpers.py

Replacing deprecated stack attribute `self.full_stack_name` with `self.name` so that using the `protect` key on a stack config does not raise an AttributeError.

Sptr 120 - Replace deprecated stack attribute

---

sceptre/helpers.py
sceptre/stack.py
tests/test_helpers.py
tests/test_stack.py

This pull request aims to simplify execution protection. It is motivated by #120 and it's PR #121, and is a "proposal" PR.
The previous implementation used a decorator, `@execution_protection`, which was applied to all "unsafe" commands (`create`, `delete` etc). The decorator code was very tightly coupled with the stack code. The decorator function assumed that: 
- the first argument passed was `self` (i.e. it could only be applied to an object)
- the object has a `dict` attribute `config`
- the object has an attribute `name`
This tight coupling makes the function difficult to test. The previous implementation mocked out `Stack` completely, so when changes were made to `Stack` (`full_stack_name` -> `name`), the fact that this decorator still used the old value wasn't picked up (#121)
This …

Simplify execution protection

---

sceptre/environment.py

Previously, when launching an environment, a stack would be launched if
all parent stacks were not in the *_FAILED state. This commit changes
this to only launch a stack if all parent stacks are in the *_COMPLETE
state. These stricter requirements fix issues which occur when a parent
stack is in an e.g. DELETE_FAILED state.

Fix launch requirements

---

sceptre/template.py

A fix for if we have a class which calls a non-existing function:
class SomeClass(object):
def __init__(self, sceptre_user_data):
self.template = Template()
self.sceptre_user_data = sceptre_user_data
self.non_existing_function()
The template generating class outputs a a misleading error:
`The template does not have the required 'sceptre_handler(sceptre_user_data)' function.`

fixed misleading \"The template does not have the required..\" error

---

sceptre/stack.py
tests/test_stack.py

This PR fixes a bug introduce in this [commit](https://github.com/cloudreach/sceptre/commit/970c118f2a18105e13e5bb370930f6e2de2ed674). The bug was where partial created environments could not be deleted with the delete-env command.

Bugfix unable to delete partial env

---

sceptre/environment.py
tests/test_environment.py

This PR make sure Environment objects being given a path with forward slashes. Fixes a bug whereby launching nested environments in a Windows environment would fail due to environment paths containing backslashes.

Bugfix for environment paths with backslashes

---

docs/docs/environment_config.md

It is clear from the surrounding text that the example directory structure was not indented correctly.

Indent directory structure properly

---

sceptre/cli.py
tests/test_cli.py

Also, adds the ability to colour any output produced by the 'write' method. However, the default behaviour (no-color) is preserved for all other cli commands.
Addresses enhancement proposed in [#7](https://github.com/cloudreach/sceptre/issues/7)

Add status colouring for output of describe-env command

---

docs/docs/stack_config.md
sceptre/config.py
sceptre/stack.py
tests/fixtures/config/account/environment/region/security_groups.yaml
tests/test_config.py
tests/test_stack.py

It would be useful to have environment_config available in the stack
config template for access to parameters like region. It would be also
a good place to define extra attributes that could be used for default
values across environment.
Adds passing enviornment_config as "environment_config" to stack
Config read.
Fixes #150 and #119.

Add passing environment_config to stack template render

---

integration-tests/sceptre-project/config/config.yaml
integration-tests/steps/templates.py
sceptre/cli.py
sceptre/stack.py
sceptre/template.py
tests/test_cli.py
tests/test_stack.py
tests/test_template.py

This PR addresses inconsistency with OOP principals within the Stack class. The `validate_template` method now resides in the Template class as `validate` - this is because the method is specific to the template. To enable this the `_get_template_details` method in the Stack class was more aptly renamed to `get_boto_call_parameter` and moved inside the Template class. The API to validate a template is now `Stack().template.validate()` rather than `Stack().validate_template()`. No new functionality has been added.
[2]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-I …

Refactor validate template

---

sceptre/environment.py
tests/test_environment.py

Now when an empty environment (folder) is encountered, an exception will be raises when loading stacks. This exception provides feedback to the developer concerning their invalid environment hierarchy. Prior to this change, various misleading exceptions could be thrown depending on the cli command and placement of the empty environment.
This addresses the issue #163

Fix misleading empty environment error

---

sceptre/cli.py
sceptre/stack.py
tests/test_cli.py
tests/test_stack.py

Although ChangeSets provides insightful information, sometimes it does not give enough information (for example when changing Instance Tags or PolicyDocuments). This diff command will show just a raw diff between the local generated template and the Cloudformation remote one.

Add Stack Diff Command

---

docs/docs/hooks.md
sceptre/hooks/asg_scheduled_actions.py
tests/test_hooks/test_asg_scheduled_actions.py

Deprecating asg_scheduled_actions hook in favor of asg_scaling_processes hook as it covers the same functionality. This PR add deprecation notices into the documentation and code.

Deprecate asg-scheduled-actions hook

---

.github/PULL_REQUEST_TEMPLATE.md

Since it's not uncommon for us to request several changes, it may solve a lot of headaches to request contributors squash commits after approval but before it's merged.

Add a note to squash commits after the changes have been approved.

---

docs/docs/environment_config.md
sceptre/connection_manager.py
sceptre/environment.py
tests/test_connection_manager.py
tests/test_environment.py

Now able to specify which iam_profile for boto3 to use, either when
assuming an iam_role, or when interacting with the environment. This is
useful when managing multiple AWS account and credentials.

[Resolve #143] Add iam_profile env config option

---

sceptre/connection_manager.py
tests/test_connection_manager.py

STS sessions are limited to maximum 1 hour, if a deploy takes
longer than this, sceptre will fail. This commit fixes this by
caching the expiry time and validating it against current time
when a call is made.
Fixes issue in #179 
------------

Recreate STS session if expired

---

sceptre/cli.py
sceptre/stack.py
tests/test_cli.py
tests/test_stack.py

This reverts commit 53f364aae48a312a337980be0fc7eb5c592ee7c2.
`sceptre diff` command is being removed. Diff was done comparing the string representations of the local template and the remote template. However, when you upload the template to AWS - its stored a JSON object and hence can be re-ordered, have whitespace changes etc - and you can’t retrieve the actual string you uploaded in the first place.

Revert "Add stack diff command (#212)"

---

docs/docs/stack_config.md
sceptre/stack.py
tests/test_stack.py

Now able to specify a list of SNS topic ARNs within a stack config using the `notifications` field. Notifications for that stack will then be sent to the specified SNS topics. This is useful for monitoring and integrating with Cloudformation.
I took a first stab at writing integration tests for this, but it raised a few questions:
- should the SNS topic be created ahead of time in the Sceptre integration account? Or should part of the setup for the integration tests be this topic creation.
- I had some trouble testing my integration tests, mainly surrounding assuming the `arn:aws:iam::458947373260:role/SceptreIntegrationTestsRole` role. My work around was to change comment out this role in all the `config.yaml` files. Is this the correct work around?
Let me know what you think! …

[Resolve #184] Add support for SNS stack notifications

---

sceptre/connection_manager.py
tests/test_connection_manager.py

Fixes re-creation of expired STS credentials when using the `iam_role`. The logic for evaluating when a session was expired was reversed, hence causing Sceptre to recreate the session on every boto call.

Hotfix for renewing assumed role sessions

---

.circleci/config.yml

Adding filter run only linting and unit tests on forked PRs.

Add external PR testing filters

---

sceptre/environment.py
sceptre/helpers.py
tests/test_environment.py

As discussed in #234, a cycle of dependencies with more than two nodes fails to be caught by _check_for_circular_dependencies. This PR updates the algorithm to a depth-first search based approach, providing a more robust circular dependency detection.
The tests, I'd imagine will need some work, as I'm new to the terrifying world of Python mocking libraries.
Additionally, I thought integration tests would be helpful, but there were no such tests for detecting circular dependencies; was this a conscious decision?
* [?] Added integration tests (if applicable).
[2]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Singl …

Update dependency resolution to detect more general cycles

---

sceptre/helpers.py

When constructing the path of encountered nodes, they were inserted
at the beginning of the list. However, when that list is trimmed
down upon finding a cycle, the logic suggested that the nodes
should have instead be added to the end.
This commits now adds nodes to the end when constructing a path.

Fix path creation when encountering stacks.

---

docs/docs/resolvers.md

Updated to accurately say the resolver name is snake-class and clarified how the resolver value is accessible in within the class.

Fix description of custom resolver syntax

---

sceptre/template.py
tests/test_template.py

Resolves #254
We require better support for different file types when uploading
tempaltes to S3. Prevously, only .json was supported, with this commit
a more generic .template extension is implemented.
This PR acts as a stop-gap solution for #255 until better handling of file extension is implemented. 

Add generic fie extension for S3 upload

---

.circleci/config.yml
Makefile
setup.cfg
setup.py

This PR enables automated deployments to PYPI via CircleCi when a version bump is committed. Also edits the long description in PYPI to not include lengthy history which causes RST parsing errors.

Enable pypi deployments from circleci

---

sceptre/config_reader.py
sceptre/helpers.py
tests/test_config_reader.py
tests/test_environment.py

This PR fixes a couple issue migrating to the new config reader API. Firstly stack names now reference the full path including environment - which broke dependency resolution. On_failure and notification parameters from stack config now are used to construct Stack objects. 

Compatibility fix for the new config reader api

---

integration-tests/environment.py
integration-tests/sceptre-project/config/1/config.yaml
integration-tests/sceptre-project/config/2/config.yaml
integration-tests/sceptre-project/config/3/config.yaml
integration-tests/sceptre-project/config/4/config.yaml
integration-tests/sceptre-project/config/5/1/config.yaml
integration-tests/sceptre-project/config/5/2/config.yaml
integration-tests/sceptre-project/config/5/config.yaml
integration-tests/sceptre-project/config/6/1/config.yaml
integration-tests/sceptre-project/config/6/2/config.yaml
integration-tests/sceptre-project/config/6/3/config.yaml
integration-tests/sceptre-project/config/6/4/1/config.yaml
integration-tests/sceptre-project/config/6/4/2/config.yaml
integration-tests/sceptre-project/config/6/4/config.yaml
integration-tests/sceptre-project/config/6/config.yaml
integration-tests/sceptre-project/config/7/config.yaml
integration-tests/sceptre-project/config/8/config.yaml
integration-tests/sceptre-project/config/config.yaml

This PR removes the assume role for integrations tests and randomizes the bucket name. These properties were specific to the account linked to CircleCI and prevented others from running integration tests locally in other AWS accounts.

[Resolve #272] Enable integration tests in generic AWS accounts

---

docs/docs/environment_config.md
sceptre/cli/__init__.py
tests/test_cli.py

Now able to specify multiple --var-file options when running
sceptre from the CLI. The dictionaries from these files will
be merged and exposed to the jinja templating. This allows
users to break a monolithic variable file into composable
pieces.
**Replace the text above the line with a summary of the changes in your PR.
The more detailed you are, the better. Before submitting the PR, make sure the following are checked.**

[Resolve #283] Add Support for Multiple --var-file Options

---

setup.py

Hotfix for the CLI not being able to run after pip installation. This adds the CLI module to the packages contained in the install. 

Hotfix for new cli not being installed correctly

---

sceptre/stack.py

This adds support for resolvers for notifications in Stacks. Allows notifications to be resolvable objects.

[Resolves #268] Add support for resolvers in the Stack object

---

sceptre/cli/create.py
sceptre/cli/describe.py
sceptre/cli/execute.py
sceptre/cli/helpers.py
sceptre/cli/list.py
sceptre/cli/policy.py
sceptre/cli/template.py
sceptre/cli/update.py

This stack removes a redundant `get_stack` function from the CLI helpers class - as the `get_stack_or_env` function provides the same functionality. 

Remove get_stack from cli helpers

---

sceptre/cli/__init__.py
sceptre/cli/helpers.py
tests/test_cli.py

Now variables supplied using the --var and --var-file command options
are available in the jinja templating as `{{ var.* }}`.
**Replace the text above the line with a summary of the changes in your PR.
The more detailed you are, the better. Before submitting the PR, make sure the following are checked.**

[Resolve #288] Fix how user variables are accessed in config templating

---

sceptre/template.py
tests/fixtures/templates/vpc.template
tests/test_template.py

This PR adds `.template` to the accepted extensions for template files. AWS samples [3] use this extension so I think it'd be reasonable to allow this as well. 
[3]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/sample-templates-services-us-west-2.html

Add template to supported file extensions

---

docs/docs/templates.md

This adds one line to the documentation to clarify the link between `sceptre_user_data` in Jinja templates and the Stack Config.

[Resolves #313] Clarify link between sceptre_user_data and stack config

---

sceptre/config_reader.py
sceptre/helpers.py
sceptre/hooks/__init__.py
sceptre/resolvers/__init__.py
sceptre/resolvers/stack_output.py
sceptre/stack.py
tests/test_config_reader.py
tests/test_hooks/test_hooks.py
tests/test_resolvers/test_resolver.py
tests/test_resolvers/test_stack_output.py

This PR adds a setup function to Hooks and Resolvers. This is to define a clearer lifecycle for these objects. Not explicit change to current functionality. Removes not so nice use of partials when reading config.

Add resolver and hook setup function

---

requirements.txt
setup.py

The restriction on Boto < 1.5.0 is starting to get really annoying due to Python's lack of isolated dependencies between versions. We want to use new versions of botocore in other projects as they have support for profile better role assumption (`source_profile` in `~/.aws/config` stuff), but we can't make other projects require new boto versions as their installation then conflicts with Sceptre.

Allow newer boto versions

---

sceptre/cli/__init__.py
sceptre/cli/template.py
sceptre/template.py
tests/test_cli.py
tests/test_template.py

Resolves #106
We need to be able to estimate the cost of our Cloudformation templates
before creating them. AWS provides a convenient API to make this happen.
This API has been implemented in Stack and the Cli to enable the use
within python modules and the CLI.
If called from the CLI, a unique URL containing the estimated cost
will be printed to stout and will attempt to open a web browser with
that URL.

Add Estimate Template Cost Functionality

---

requirements.txt
setup.py

Resolves issue with Sceptre used as a library that was conflicting with using current stable releases of Jinja2 (latest is 2.10x).

[Resolve #351] Allows jinja2 >=2.8, for upgrades

---

contrib/bash-completion/README.md
contrib/bash-completion/sceptre

[Resolve #287 ]Add the sceptre completion script to the contrib folder along with a README file.

contrib: add bash-completion script

---

docs/docs/stack_config.md
integration-tests/features/create-stack.feature
integration-tests/features/update-stack.feature
integration-tests/sceptre-project/config/8/C.yaml
integration-tests/sceptre-project/config/config.yaml
integration-tests/sceptre-project/templates/updated_template_wait_300.json
integration-tests/sceptre-project/templates/valid_template_wait_300.json
integration-tests/steps/stacks.py
sceptre/config_reader.py
sceptre/stack.py
tests/test_config_reader.py
tests/test_stack.py

Added a stack_timeout key in stack yaml config files. Allow timeout and auto-rollback of stucked cloudformation deployments.
For stack creations: timeout is simply passed in the underlying create_stack boto3 call using the TimeoutInMinutes parameter. Cloudformation solely handles the timeout behavior.
For stack updates: wait_for_completion takes the timeout in as an optional parameter. If elapsed time overreach the timeout, a cancel_update_stack call is performed.
Hope this can be found useful by others. Still a lot of love for Sceptre here at Ubisoft, cheers!
* I removed the default profile value because it crashes most of the tests right now.

Adding stack_timeout (same code as PR #300 with integration tests fixed)

---

.circleci/config.yml

We have been seeing a number of 'Resetting dropped connection' in our
integration tests due to throttling on AWS's side. This commit lowers
the number of parallel runs of the integrations tests, in an attempt to
resolve this issue.

[Resolves #271] Decrease circleci parallel runs

---

CONTRIBUTING.rst

Instructions have been added about how to setup a sceptre fork with
CircleCi. Currently, there is no visability of integration tests for a
forked PR. We only find out whether the PR has passing integration
tests after they are merged into master.
Setting up integration tests in CircleCi is very quick and running them
is free. The cost of asking contributors to set this up outweighs the
cost of dealing with the repercussions of merging bad branches.

[Resolves #382] Setup integration tests for contributors

---

Makefile
docs/_api/conf.py
integration-tests/steps/helpers.py
requirements.txt
setup.cfg

Add flake8-per-file-ignores to requirements to ignore:
Long lines and duplicated defines needed for behave
docs/_api/config.py to comment the config consistently
set max-complexity to 12 to protect code quality

[Resolves #336] Lint integration tests and docs (#320)

---

behave.ini
integration-tests/environment.py
integration-tests/features/stack-output-external-resolver.feature
integration-tests/features/stack-output-resolver.feature
integration-tests/sceptre-project/config/1/A.yaml
integration-tests/sceptre-project/config/6/2/A.yaml
integration-tests/sceptre-project/config/6/2/B.yaml
integration-tests/sceptre-project/config/6/2/C.yaml
integration-tests/sceptre-project/config/9/A.yaml
integration-tests/sceptre-project/config/9/B.yaml
integration-tests/sceptre-project/config/9/aws-config
integration-tests/sceptre-project/templates/dependencies/dependent_template_local_export.json
integration-tests/steps/helpers.py
integration-tests/steps/stacks.py
sceptre/config_reader.py
sceptre/connection_manager.py
sceptre/environment.py
sceptre/helpers.py
sceptre/resolvers/stack_output.py
sceptre/stack.py
tests/fixtures/config/config.yaml
tests/test_config_reader.py
tests/test_connection_manager.py
tests/test_resolvers/test_stack_output.py
tests/test_stack.py

This will deprecate the original functionality of using `iam_role` and instead allow the user to use an AWS Profile (supported by `boto` and `awscli`). The profile itself is usually defined in the `~/.aws/config` file (prefixed with `profile <name>`) but could be placed anywhere with the use of `AWS_CONFIG_FILE` which specifies the path to the configuration file.
This will break any sort of compatibility with the use of `iam_role` and instead a profile has to be created. The profile can be added to the sceptre configuration file in the same manner as the `iam_role` used to. 
The current level of precedence is as follows (and is all according to the default AWS Config/CLI behaviour linked below):
1. Environment variable credentials take priority over profiles
2. Region specified in the …

[Resolves #257] improved Cross Region/Account Support

---

contrib/kms-resolver/README.md
contrib/kms-resolver/kms.py
contrib/ssm-resolver/README.md
contrib/ssm-resolver/ssm.py
sceptre/cli.py
sceptre/exceptions.py

Previously, error messages were vauge when trying to take action on
non-leaf environments. This commit adds better error handling with a
more useful message for the end user.

[Resolves #249] Add error message for non-leaf env

---

setup.py

Contributions are in the same repo as core sceptre therefore it's
versioned with core sceptre.  This would mean that it should also
be released with sceptre.

[Resolves #438] Add contrib to the sceptre package

---

sceptre/environment.py
tests/test_environment.py

As highlighted in #187, a user must specify a full path for stack
dependencies, even within the same environment. The documentation
shows the initial intention was to allow a user to reference the
stack name without the full path.
Given the following project structure:
config/
- config.yaml
- dev/
- vpc.yaml
- subnet.yaml
- templates/
- vpc.yaml
- subnet.yaml
Previously, a user had to specify dependencies in one of two ways:
```
dependencies:
- dev/vpc
- {{ environment_path.0 }}/subnet
```
This commit means that users can now specify dependencies as:
```
dependencies:
- vpc
- dev/subnet
- {{ environment_path.0 }}/xyz
```

[Resolves #187] Fix launch env dependency path

---

sceptre/connection_manager.py
tests/test_connection_manager.py

There was a small issue introduced with the cross region support, namely if providing temporary AWS creds then it wouldn't work as the AWS session token was never included in the config manager when supplied via environment variables.

[Resolves #439] Add session token to connection manager config

---

sceptre/config.py
sceptre/strategies.py

Previously, the `dependencies` data structure in stacks were not being merged properly. This resulted in issues, such as #298, being reported. For example, in the sceptre project displayed below, if `bundle/b/y.yaml` had a `!stack_ouput` from `bundle/a/x.yaml` an implicit dependency is created. If we then specified that `bundle/b/y.yaml` had a dependency on `bundle/a/x.yaml` the dependencies would not resolve properly. 
```
.
├── config
│   ├── bundle
│      ├── a
│      │   └── x.yaml
│      ├── b
│      │   └── y.yaml
│      ├── c
│      │   └── z.yaml
│      └── config.yaml
│   
├── templates
   └── template.json
```
The fix submitted with this commit gives us flexibility in dealing with different merge strategies for config items, if required in the future. 
and …

[Resolves #298] Fix stack config dependencies merging

---

sceptre/stack.py

There does not appear to be a suitable exception returned by AWS when
attempting to delete a change-set that does not exist. The AWS API
returns a 200 regardless of whether the change-set existed or not.
Therefore the best we can do is signal to the user that if the
change-set existed it has been deleted.

[Resolves #160] Improve output message for delete-change-set

---

docs/docs/stack_config.md

Previous authors had wanted to remove cascading config and added a
warning about this to the docs. This is no longer the case so removing
the warning.

[Resolves #458] Remove depreciation warning

---

docs/Gemfile
docs/Gemfile.lock

Adds a fix for CVE-2018-17567
More information: moderate severity
Vulnerable versions: < 3.6.3
Patched version: 3.6.3
Jekyll through 3.6.2, 3.7.x through 3.7.3, and 3.8.x through 3.8.3 allows attackers to access arbitrary files by specifying a symlink in the "include" key in the "_config.yml" file.
Adds fix for CVE-2018-1000201
More information: moderate severity
Vulnerable versions: < 1.9.24
Patched version: 1.9.24
ruby-ffi version 1.9.23 and earlier has a DLL loading issue which can be hijacked on Windows OS, when a Symbol is used as DLL name instead of a String This vulnerability appears to have been fixed in v1.9.24 and later.

Patch for CVE-2018-17567 and CVE-2018-1000201

---

sceptre/cli/create.py
sceptre/cli/delete.py
sceptre/cli/describe.py
sceptre/cli/execute.py
sceptre/cli/launch.py
sceptre/cli/list.py
sceptre/cli/policy.py
sceptre/cli/status.py
sceptre/cli/template.py
sceptre/cli/update.py
sceptre/plan/__init__.py
sceptre/plan/executor.py
sceptre/plan/plan.py
sceptre/plan/type.py
sceptre/template.py
tests/test_cli.py
tests/test_plan.py

Add SceptrePlan and Executor
This PR is part of a wider piece of work that changes the way
Sceptre will load and execute commands on stacks and stack groups.
Between this commit and bf39d57f1591911799aad985f8e748fb7e2b8b4b sceptre
will be able to preload all the objects and configuration necessary to
execute an action, rather than taking actions on-the-fly, which is the
behaviour in version 1.

Implement SceptrePlan and Executor

---

sceptre/cli/__init__.py
sceptre/cli/new.py
sceptre/config/reader.py
sceptre/helpers.py
tests/test_cli.py

A small rename of `init` cli command group to `new`

Change cli init to new

---

sceptre/cli/helpers.py

Removes unnecessary CLI output from printing, mainly `... sceptre.plan.actions ...`

Remove unnecessary CLI output

---

sceptre/config/reader.py
sceptre/stack.py
tests/fixtures-vpc/config/config.yaml
tests/fixtures/config/account/stack-group/config.yaml
tests/fixtures/config/account/stack-group/region/config.yaml
tests/fixtures/config/account/stack-group/region/construct_nodes.yaml
tests/fixtures/config/account/stack-group/region/security_groups.yaml
tests/fixtures/config/config.yaml
tests/fixtures/config/top/level.yaml
tests/test_config_reader.py

At some point when rewriting to version 2 the StackGroup config was not being included in full during the template generation. This PR add the stack_group config back in to the template generation and updates the CONFIG_MERGE_STRATEGIES accordingly.

Add StackGroup Config variables to template renderer

---

sceptre/config/reader.py

`notifications` and `on_failure` were omitted from `ConfigAttributes` and `CONFIG_MERGE_STRATEGIES` during the refactor. Adding them in.

Add missing attributes to ConfigAttributes

---

sceptre/cli/delete.py

Delete message was displaying `Do you want to delete_change_set ...` where it should just be 
`Do you want to delete ...`

Fix delete stack confirmation message

---

integration-tests/steps/change_sets.py
integration-tests/steps/stack_groups.py
integration-tests/steps/stacks.py
sceptre/cli/describe.py
sceptre/cli/helpers.py
sceptre/cli/list.py
sceptre/plan/actions.py
tests/test_actions.py
tests/test_cli.py

Output for `list`actions has been improved slightly by including
stack names in the output.
Output for `describe` actions has been fixed so that YAML and JSON
is properly formatted.

Fix `list` and `describe` cli output

---

docs/docs/hooks.md
docs/docs/resolvers.md

The documentation was missing `py_modules` in `setup.py` for custom resolvers. Omitting this meant that custom resolver modules were not "discoverable" outside of their local scope and therefore, Sceptre was unable to load them. 

[Resolves #539] Update docs for Custom Resolver `setup.py`

---

sceptre/cli.py
tests/test_cli.py

The update-stack-cs command always exited with a `0` (success)
irrespective of whether the change-set executed successfully or not.
This commit updates the behavior to be consistent with `update-stack`
by checking the status of the stack after the change-set execution
is complete.

[Resolves #414] Fix CLI return for update-stack-cs

---

docs/docs/cli.md
docs/docs/environment_config.md
docs/docs/stack_config.md
sceptre/cli.py
tests/test_cli.py

This PR introduces the following new commands:
* `print-env-config`
This command prints the final Environment configuration as YAML after resolving all cascaded configurations and templates.
* `print-stack-config`
This command prints the final Stack configuration as YAML after resolving all templated variables and/or custom/standard resolvers. Note that the YAML output does not include any `hooks` configurations.

[Resolves #344] New `print-env-config` and `print-stack-config` commands

---

sceptre/config.py
sceptre/hooks/__init__.py
sceptre/hooks/cmd.py
sceptre/resolvers/__init__.py
sceptre/resolvers/environment_variable.py
tests/fixtures/config/account/environment/region/nested_stack_output.yaml
tests/fixtures/resolvers/join.py
tests/test_config.py
tests/test_environment.py
tests/test_hooks/test_hooks.py
tests/test_resolvers/test_resolver.py

Rebase of #141 . See original by @sftrabbit for details.

[Resolve #140]: for V1: Nonscalar arguments for hooks and resolvers. 

---

docs/docs/stack_config.md
docs/docs/stack_group_config.md
sceptre/config/reader.py

In v1 `environment_path` was accessible as a list in templates,
split by the path separator.
In v2 the `environment_path` is known as the `command_path`. This
commit adds support for accessing the `command_path` back in to
Sceptre. For example, the user can now access parts of the
`command_path` in templates like {{ command_path.0 }}.

Fix accessing stack group

---

docs/docs/resolvers.md

In v1 stack_output resolver could only reference outputs from Stacks
within the same environment. In v2 stack_output can reference outputs
from any Stack in the Sceptre project.

[#Resolves 556] Clarify docs on stack_output resolver

---

sceptre/stack.py

This removes the extra timestamp on the right when cloudformation is running.
I'm submitting a PR for both v1/v2 as it seems like the log line contains duplicated timestamp in v1 and v2.

[Resolve #573] Remove duplication of timestamp (v1)

---

sceptre/plan/actions.py

This removes the extra timestamp on the right when cloudformation is running.
I'm submitting a PR for both v1/v2 as it seems like the log line contains duplicated timestamp in v1 and v2.

Issue 573: Remove duplication of timestamp (v2)

---

requirements.txt
setup.py
tests/test_cli.py
tests/test_template.py

In PyYAML before 4.1, the yaml.load() API could execute arbitrary code.
In other words, yaml.safe_load is not used.

Fix CVE-2017-18342

---

sceptre/cli/list.py
tests/test_cli.py

Envvar output in `sceptre list outputs...` was broken from 2.0.0. This PR resolves fixes this issue so that environment variables can be set from outputs as follows:
```bash
eval $(sceptre list outputs STACK -e envvar)
```

[Resolves #576] Fix envvar output

---

sceptre/stack.py
tests/test_stack.py

Previously, dict and list types were contained within strings in
`sceptre.stack.Stack.__repr__()`. This commit removes the strings so that
a `stack.__repr__()` can be used to create a stack using `eval()`.

[Resolves #570] Improve Stack.__repr__()

---

requirements.txt
sceptre/cli/create.py
sceptre/cli/delete.py
sceptre/cli/describe.py
sceptre/cli/execute.py
sceptre/cli/launch.py
sceptre/cli/list.py
sceptre/cli/new.py
sceptre/cli/policy.py
sceptre/cli/status.py
sceptre/cli/template.py
sceptre/cli/update.py
setup.py

bumping click to 7.0 that allows truncation of docstrings.
additionally, moved some of the docstrings to short_help to avoid repetition.
finally, minor fix to one of the docstrings.

[Resolves #607] format docstring for better --help

---

sceptre/cli/new.py
sceptre/config/reader.py

When parsing stacks and groups containing symbolic links the links were not being followed due to `os.walk()` not following symbolic links by default.  This pull request enables link following for uses of `os.walk()`.

[Resolves #634] Symlink support for v2

---

sceptre/cli/helpers.py

Use `yaml.safe_dump` to only output plain YAML instead of Python objects.

[Resolves #630] Use yaml.safe_dump Everywhere

---

integration-tests/features/create-change-set.feature
integration-tests/features/create-stack.feature
integration-tests/features/update-stack.feature
integration-tests/sceptre-project/config/10/A.yaml
integration-tests/sceptre-project/config/11/A.yaml
integration-tests/sceptre-project/templates/sam_template.yaml
integration-tests/sceptre-project/templates/sam_updated_template.yaml
integration-tests/steps/change_sets.py
sceptre/plan/actions.py
tests/test_actions.py

CloudFormation requires the CAPABILITY_AUTO_EXPAND permission in order to execute the SAM template transform (see issue #538 and #324). This PR adds this permission to the create stack, update stack, and create change set plan actions.

[Resolves #324] Add CAPABILITY_AUTO_EXPAND permission to enable transforms for SAM templates

---

.gitignore
sceptre/config/reader.py
sceptre/exceptions.py
tests/test_config_reader.py

Signed-off-by: Brendan Devenney <brendan.devenney@cloudreach.com>
There are some unanswered questions to consider when reviewing this PR:
* Should the code be differentiating between Stack Config and Stack Group Config for the user's benefit? I'm a little thrown off by the fact you can successfully deploy a Stack without any files in the tree named `config.yaml`, despite the implication that `config.yaml` is mandatory in the [StackGroup Config](https://sceptre.cloudreach.com/latest/docs/stack_group_config.html) docs. Effectively, you can store all of your config in `vpc.yaml` and Sceptre won't complain.
* Do we care enough about invalid keys to add these checks? My opinion is yes, as a typo in a stack's config could be masked due to the attribute cascading down from a parent directory. …

[Resolve #623] Catch missing config attributes

---

requirements.txt
sceptre/__init__.py
tox.ini

Note that this commit suppressed DeprecationWarnings due to dependencies
which have not yet updated their use of collections.abc.
Signed-off-by: Brendan Devenney <brendan.devenney@cloudreach.com>
Resolves #622
* Upgrades the necessary dependencies to versions which support Python 3.7.
* Adds py37 as a Tox target.
* Silences deprecation warnings to prevent [PyYAML #202](https://github.com/yaml/pyyaml/issues/202) polluting Sceptre output.

Resolve #622: Add official Python 3.7 support

---

sceptre/cli/list.py
tests/test_cli.py

Fixed cli list output issue where the export would failed if contained spaces or certain special characters

Fixed cli list output issue

---

sceptre/config/reader.py
sceptre/template.py
tests/test_config_reader.py
tests/test_template.py

adding support for s3 in china region because the url for the s3 in china is different

[Resolves #494] Add support for s3 in china regions

---

requirements.txt
sceptre/cli/helpers.py
setup.py

Updates the PyYaml version to 5.1.
Adds in YamlLoader as per https://github.com/yaml/pyyaml/issues/292
Other incompatible changes were reviewed
(https://github.com/yaml/pyyaml/issues/265) and the yaml.Loader appears
to the be only concern for now.
[Resolves #665]

Upgrade to PyYaml 5.1

---

docs/docs/hooks.md

When writing a hook I ran into a issue where documented properties weren't in the Hook base class. Traced this to a similar issue with resolvers #548

Update custom hook docs

---

sceptre/config/reader.py
sceptre/context.py
sceptre/exceptions.py
sceptre/helpers.py
sceptre/plan/actions.py
sceptre/plan/plan.py
sceptre/resolvers/stack_output.py
sceptre/stack.py
setup.py
tests/test_actions.py
tests/test_context.py
tests/test_helpers.py
tests/test_plan.py
tests/test_stack.py

The intention is to avoid unnecessary path manipulation between the end user and executing a command. In v1 [`_validate_path`](https://github.com/cloudreach/sceptre/blob/v1/sceptre/environment.py#L75) was responsible for this. Users of any operating system should now be able pass paths with native separators and sceptre work as intended.

[Resolves #531] Normalise os paths

---

CHANGELOG.md
sceptre/__init__.py
sceptre/resolvers/stack_output.py
sceptre/stack.py
setup.cfg
tests/test_resolvers/test_stack_output.py

There seemed to be a recursion issue which was probably an issue with
when a ResolvableProperty was called.
This commit attempts to fix this, however there may still be an underlying
issue. If there is then the real fix will be to try and remove
ResolvableProperties in favour of another implementation, they seem to
be causing more issues than they are worth.
Thanks to @michaetto, @zaro0508, @pha6d and @m1keil for contributing to this fix.
[Resolves #558]

Move connection_manager to stack

---

sceptre/config/reader.py

Bug fix for issue https://github.com/cloudreach/sceptre/issues/703
When using sceptre on windows, the stack name can contain backslashes. If using a deployment S3 bucket then these backslashes can end up in the S3 url, which causes the template to fail validation.
`sceptre --debug launch dev/mystack.yaml -y`
The output looks like this:
```
[2019-05-13 11:04:02] - Uploading template to: 's3://mybucket/myprefix/dev\mystack/2019-05-13-10-04-01-977892Z.json'
[2019-05-13 11:04:02] - s3-deployment - Template URL: 'https://mybucket/myprefix/dev\mystack/2019-05-13-10-04-01-977892Z.json'
An error occurred (ValidationError) when calling the UpdateStack operation: TemplateURL must be an Amazon S3 URL.
```
The fix is to replace any backslashes in the stack name with forward slashes when resolving the …

Bug fix for issue with backslash in S3 url on windows

---

sceptre/cli/__init__.py
sceptre/cli/helpers.py
sceptre/cli/list.py
sceptre/cli/template.py
tests/test_cli.py

Set JSON to be the general default CLI output value where appropriate.
Resolves #673 #708 

Update CLI to use JSON as default output format

---

integration-tests/steps/stacks.py
sceptre/plan/actions.py
tests/test_actions.py

Related to #678
I saw your commit c3ec5d9818a @ngfgrant and had a few concerns with it. Especially the "catch any exception" part. Also the `None` return caused on exceptions I think is a mistake.
Instead of special handling no changes updates in the launch method I've moved that logic into the update method.

Improve stack update for no changes

---

sceptre/resolvers/stack_output.py
tests/test_resolvers/test_stack_output.py

Fixes #725 by making the `stack_output` resolver use the `project_code` of the dependent stack instead of its own `project_code`.

[Resolve #725] fix overwritten project_code in stack_output dependencies

---

integration-tests/features/generate-template.feature
integration-tests/sceptre-project/templates/valid_template_func.yaml
integration-tests/steps/templates.py
sceptre/cli/helpers.py

In cases where Cloudformation-specific tags were used (like !GetAtt, for
example), sceptre would fail to generate yaml and json output when `sceptre
generate` was called.
Here we use the loaders provided by Amazon's cfn-lint package to properly read
the cloudformation yaml after substitution, so that we can translate it to yaml
and json correctly without error.
A potential issue with this approach is that I used cfn-lint as a library to provide functionality for resolving all of the custom tags in cloudformation. There aren't any guarantees that I'm aware of for the stability of this API, but it will work at the pinned version. In service of this particular problem, I opened up an issue [here](https://github.com/aws-cloudformation/cfn-python-lint/issues/831) about this, since having a cfn …

Resolve #658: Generate non-trivial json and yaml

---

sceptre/cli/__init__.py
tests/test_cli.py

Previously, the `--var` flag would not support nested dictionary
overwriting. For example, a variable file such as
```
vars.yaml
---
top:
middle:
nested: hello
middle2:
nested_2: world
```
and a CLI command:
`sceptre --var-file vars.yaml --var top.middle.nested=hi launch
dev`
would result in a failure as `top.middle.nested` would be treated as
the full key name in the dictionary but jinja would attempt to parse
the `.`'s  as keys.
This commit fixes that behaviour by enabling support for `.` separated
strings that represent keys in a nested dictionary.
Thus `--var top.middle.nested=hi` would be treated as:
```
top: {
middle: {
nested: hi
}
}
```
[Resolves #641]
[Guide to writing a good …

Fix support for nested dicts in CLI --var flag

---

tests/test_cli.py

This test is a little annoying anyway so may remove it in the future but for now changing the url to open the sceptre docs rather than example.com

Change example url to sceptre homepage

---

sceptre/config/graph.py

This fixes #788: Debug output of dependency graph misses stack name and edge name .
The correct variables are now used in the debug output so that the stack names are displayed properly.

[Resolves #788] Debug output of dependency graph misses stack name and edge name

---

CHANGELOG.md
sceptre/resolvers/__init__.py
sceptre/stack.py
tests/test_resolvers/test_cache.py
tests/test_stack.py

Resolving Stack.sceptre_user_data for the first time could explode the
stack if a resolver contained a reference to .sceptre_user_data.
The fix introduces a 2-pass resolution of that property to avoid the
problem.
Reopening PR "Fix infinite recursion in sceptre_user_data" #787. Changed mind and will merge it here as well as sceptre-core

[Resolve #733] fix infinite recursion

---

docs/_source/docs/faq.rst
docs/_source/docs/stack_config.rst
docs/_source/docs/stack_group_config.rst
docs/_source/docs/templates.rst

As mentioned in the issue, there are a lot of raw and endraw tags around that are not replaced during the doc build. Looking at this, I also saw that the type of code block could be changed to yaml in many cases for better readability.

[Resolve #785] Clean up code blocks in doc

---

docs/Makefile

Before this commit, during installation there is an error message about missing dependencies (`sphinx-build` or, if this is present, `sphinx-apidoc`).
Root cause is that a `clean` target is missing from docs/Makefile. From the main Makefile target `docs-clean` this target is called, but ends up in the catch-all target which needs sphinx-build.

[Resolves #686] Add docs clean target

---

docs/_source/docs/get_started.rst
docs/_source/docs/stack_config.rst

YAML has replaced JSON as a more popular format for writing Cloudformation templates, this should be reflected in the documentation.

Replace JSON with YAML as default Cloudformation format in doc

---

docs/_source/_templates/versions.html

Fixes #833 
This fix will generate version urls from the origin to the version number which results into on every page:
```
origin: https://sceptre.cloudreach.com 
version number: 2.2.1
result: https://sceptre.cloudreach.com/2.2.1/
```
Additionally we could think of a slight improvement by adding "path" prefix for the future if needed.
E.g. 
```
origin: https://sceptre.cloudreach.com 
version number: 2.2.1
prefix: docs
result: https://sceptre.cloudreach.com/docs/2.2.1/
```

Fix version links

---

.circleci/documentation-versions.py

This update prevents github-pages script to delete specific versions.
Which is needed for docs of `1.5.0`.
Merge this before https://github.com/Sceptre/sceptre.github.io/pull/2

Allow to keep specific versions of docs

---

sceptre/config/reader.py
sceptre/template.py
tests/test_config_reader.py

Template engines have an HTML autoescape mechanism that protects web
applications against most common cross-site-scripting (XSS)
vulnerabilities.
By default, it automatically replaces HTML special characters in any
template variables. This secure by design configuration should not be
globally disabled.
Escaping HTML from template variables prevents switching into any
execution context, like <script>. Disabling autoescaping forces
developers to manually escape each template variable for the application
to be safe. A more pragmatic approach is to escape by default and to
manually disable escaping when needed.
A successful exploitation of a cross-site-scripting vulnerability by an
attacker allow him to execute malicious JavaScript code in a user's web
browser. The most severe XSS attacks …

Fix Jinja autoescape vulnerability

---

integration-tests/sceptre-project/config/9/B.yaml
integration-tests/sceptre-project/config/9/aws-config
sceptre/config/reader.py
sceptre/connection_manager.py
sceptre/plan/actions.py
sceptre/resolvers/stack_output.py
sceptre/stack.py
tests/test_config_reader.py
tests/test_connection_manager.py
tests/test_resolvers/test_stack_output.py
tests/test_stack.py

This is to resolve #571 / #796 
The functionality for `iam_role` has been re-introduced into the stack config and can be used at any level in the stack config (child overrides parent).
I've kept the precedence pretty much the same, the only difference is that if you specify `iam_role` then that role is assumed after Sceptre creates the session (either using environment variables, profile or local credentials). This follows what was written [here](https://github.com/Sceptre/sceptre/issues/571).
In addition, I've added support for additional arguments for the `stack_output_external` resolver, initially it would allow a profile argument only:
` !stack_output_external StackName::StackOutput my-profile`
This has now changed to support the following:
- `!stack_output_external …

[Resolves #571] Add iam_role capability for stack-config

---

docs/_source/docs/cli.rst
docs/_source/docs/terminology.rst

Fixup formatting of Terminology heading. This currently reflects as a rendering error in the public docs, on https://sceptre.cloudreach.com/2.2.1/docs/terminology.html

Fix formatting error in terminology.rst

---

sceptre/connection_manager.py

Importing with a "." causes plugin builds to fail with an ImportError.
Change the "." to a path name.

[Resolve #848] Fix imports

---

sceptre/config/reader.py
sceptre/exceptions.py
tests/test_config_reader.py

Broke the list comprehension apart because otherwise we can't get info on the current iteration (dependency name).
Had to take the edited part out as a separate function because construct_stacks was getting too complex according to make lint.
Unit test is still missing, please let me know if my general approach is ok and I'll add it.
I set up a small test repo that replicates the issue here: https://github.com/uhinze/sceptre-stackoutput

[Resolves #758] Improve error message for stack_output dependencies

---

sceptre/template.py
tests/fixtures/templates/chdir.py
tests/test_template.py

Before this, the _call_sceptre_handler method makes multiple calls to
os.getcwd() in determining paths to add and then later paths to remove.
In the event that the sceptre_handler code then makes a call to
os.chdir, the second call ends up removing the wrong path.
This patch ensures that the paths removed are the same ones that are
added.

[Resolve #870] Bugfix in _call_sceptre_handler

---

docs/_source/docs/hooks.rst
docs/_source/docs/resolvers.rst
sceptre/config/reader.py
tests/test_config_reader.py

Allow hooks and resolvers to take complex data objects as arguments.
This is a port of commit ed681aa9 to Sceptre V2

[Resolves #798] complex data for resolvers and hooks

---

sceptre/config/reader.py
tests/test_config_reader.py

When specifying a `command_path` for cli operations, commands will be executed on all stack-groups which share a prefix with `command_path`. So, if you have two configs `env1` and `env2`, but then provide `env` as your `command_path`, both `env1` and `env2` will be executed.
In my opinion, `env` is not a valid stack-group and should therefore not start anything. We should either specify `env1` or `env2` expicitly or alternatively group them under one common directory `my-envs` when you want to launch stack together.

[Resolve #546] select command stacks based on exact stack-group name

---

sceptre/plan/actions.py

Our execute change-set command was attempting to execute all change sets
even if the change-set creation had failed due to no changes.
This commit adds a filter for change-sets that have failed because there
are no changes. Information is logged to the user and sceptre continues
launching all change-sets that were successfully created.
[Resolves #846]

Fix execution on empty change-sets

---

docs/_source/docs/hooks.rst
sceptre/plan/actions.py

Add hooks to create_change_set
Adds before_create_change_set and after_create_change_set hooks.
These are used for "update -c" or "create" for change set.
Hooks for create_change_set are necessary for actions that need to
happen before any update. For example, upload templates for nested
stacks.

Create_change_set hooks

---

requirements/dev.txt
requirements/prod.txt
setup.py

This is a fix for https://github.com/Sceptre/sceptre/issues/916.
**NOTE:** This should not be merged until https://github.com/Sceptre/sceptre/issues/893 is fixed, because `networkx>2.1` is not available for 2.7. 

Bump networkx to 2.4

---

docs/_source/docs/hooks.rst
sceptre/plan/actions.py

This enables `before_generate` and `after_generate` hook actions to
allow users to execute hooks when running the `generate` command.

[Resolves #874] Allow generate command to run hooks

---

requirements/prod.txt
setup.py

sceptre fails to install when installed after awscli. make colorama
dependency more flexible so that it will not fail.

[Resolves #947] make colorama dependency more flexible

---

docs/_source/docs/stack_config.rst

A warning about error prone handling of duplicate parameters in Stack Config.

Warn about duplicate stack config parameters in documentation

---

.circleci/config.yml

This PR updates the docker image for the following:
1. Python 2.7 support was removed from `cloudreach/sceptre-circleci` docker image in commit
https://github.com/Sceptre/sceptre-circleci/commit/975fa092fdd3f005bb4f714f7aa0a736ec1a75a3
and tagged with https://github.com/Sceptre/sceptre-circleci/releases/tag/v0.5.0
We removed python 2.7 support from sceptre in PR #922 however we neglected to update
cicleci to build with the updated docker image.   We update the docker image to use the updated
sceptre-circleci container with python 2.7 removed.
2. The build is failing due to building in an Alpine 3.7 docker container.  We update to pick up
PR https://github.com/Sceptre/sceptre-circleci/pull/1 to allow sceptre build to build in a Alpine 3.11
container.
This PR depends on PR …

[Resolves #921 and #956] Remove Python 2.7 support and fix build

---

.circleci/config.yml

Trigger a circlci build on every PR.  It will run build sceptre,
lint scepter code, run sceptre unit-tests, and build sceptre docker image.
All tasks which do not require secrets.

Trigger builds on PRs

---

docs/_source/docs/stack_config.rst

A [test case](https://github.com/Sceptre/sceptre/blob/40829c0b6de08816a2fc1073101d2da18d88d259/tests/fixtures/config/account/stack-group/region/security_groups.yaml#L5) suggests that change
Simple fix to the docs.

Fix docs about stack group config in templates

---

.circleci/config.yml

CircleCi reported `build` job as unauthorized[1] because it had a context
applied to it.  PR builds do not require a context for build,
lint-and-unt-tests, and build-docker-image jobs.
[1] https://support.circleci.com/hc/en-us/articles/360050273651-Builds-Unauthorized-due-to-contexts

remove circleci context

---

.circleci/README.md
.circleci/config.yml
integration-tests/features/stack-output-external-resolver.feature
integration-tests/sceptre-project/config/9/aws-config

Fix up the CI and re-enable integration tests to run against a temporary
AWS account.

re-enable integration tests

---

docs/_source/docs/templates.rst

Sceptre can generate cloudformation templates from AWS CDK code
without much effort. Adding documention on how to use sceptre
to drive AWS CDK python files.

Add documentation for AWS CDK

---

setup.py

We currently only run tests on python 3.6 and 3.7

remove python 3.5 from supported list

---

docs/_source/docs/get_started.rst
docs/_source/docs/stack_group_config.rst

The docs seem to imply that the user knows that Sceptre uses the same
configuration as the AWS CLI and thus does not provide details on how
to set it up for the first time.
This patch clarifies that by explicitly noting to use the AWS CLI to
configure the configuration files and links to the source docs.

Add info to configure Sceptre's API Access

---

.cfnlintrc
.cfnlintrc.yaml
.pre-commit-config.yaml
integration-tests/sceptre-project/templates/valid_template_func.yaml

Run cfn-lint[1] check with pre-ccommit to validate cloudformation
templates.
[1] https://github.com/aws-cloudformation/cfn-python-lint

add cfn-lint to pre-commit checks

---

.github/ISSUE_TEMPLATE.md

Setup a github template[1] for sceptre issues to guide people reporting
issues to sceptrw.
[1] https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
reporting issues to sceptr.e enter the commit message for your changes. Lines starting

GH template for sceptre issues

---

.circleci/config.yml

The tag workflow was not deploying to sceptre to pypi automatically.
Fix to automatically deploy sceptre to pypi automatically.  Also run
the correct targets to publish docs and docker image.

Fix circleci tag workflow

---

.cfnlintrc
.gitignore
.pre-commit-config.yaml

Passing in cfn-python-lint options with .cfnlintrc file doesn't seem to work
when used with pre-commit.  However passing options from the pre-commit
config file does work.  We change to pass in the options with the prec-commit
config file which will allow us to use the latest version of cfn-python-lint.

Fix pre-commit cfn-python-lint

---

.circleci/config.yml

Twine is already installed by `pip intall requirements/dev.txt"
therefore it doesn't need to be install again.

Remove duplicate install of twine

---

README.md

The main goal here was just to add some more informational badges to the README. Since we're not currently using any kind of "code quality" service, none of those are available right now. But those can easily be added in the future if that situation changes.
While I was in the README, I fixed the few `markdownlint` warnings that popped up. I debated on adding `markdownlint` to the `pre-commit` toolchain, but I hesitated as there is not an active project written in Python and I did not want to add another language to the build toolchain. If that is wanted however, we have the following options:
* [Run the canonical Ruby linter](https://github.com/markdownlint/markdownlint/blob/master/.pre-commit-hooks.yaml#L1-L6)
* [Run the canonical Ruby linter in …

Add new badges & clean up README structure

---

README.md

Sceptre V1 EOL was on 06/01/2019.  Remove docs for V1

Remove Sceptre V1 docs

---

sceptre/config/reader.py
sceptre/template.py
tests/test_config_reader.py
tests/test_template.py

S3 virutal-hosted-style urls include the region name.
Currently, template.py only properly formats urls in
the China region. This commit adds the region to the url.
In doing so, gov cloud becomes supported.

[Resolves #1013] Fix virtual-hosted-style uri

---

sceptre/cli/helpers.py

When running `sceptre generate` the output has extra padding.
This seems to be the difference between:
R    e    s    o    u    r    c    e    s    :
S    a    m    A    p    p    :
T    y    p    e    :         A    W    S    :    :    S    e    r    v    e    r    l    e    s    s    :    :    A    p    p    l    i    c    a    t    i    o    n
and:
Resources:
SamApp:
Type: AWS::Serverless::Application

[Resolves #1032] Generate text output unnecessary padding

---

tests/test_cli.py

The cost estimate command opens a web browser as part of the command
call. This patch overrides that to prevent tests from actually starting
a real browser window while running tests.

fix: Do not open a web browser during test

---

docs/docs_requirements.txt
requirements/dev.txt
requirements/prod.txt
setup.py

This PR adds click==8.0+ support 
To support click=>8.0 we needed to update Sphinx, sphinx-click 
and sphinx_rtd_theme libraties since sphinx-click depends on a specific version of click.

[Resolve #1050] Update click version

---

docs/_source/docs/templates.rst

According to CDK documentation the get_stack() API is deprecated and
they recommend switching to get_stack_by_name() instead.
Ref: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.cx_api/CloudAssembly.html#aws_cdk.cx_api.CloudAssembly.get_stack

Use get_stack_by_name() instead of get_stack()

---

sceptre/config/reader.py
tests/test_config_reader.py

Fix for: #1042 
This changes the `ConfigReader` to always use the `full_command_path` instead of using `full_config_path` then add the stack dependencies to the `todo` set to be processed.
I tested locally in my environment with over about 2,500 Sceptre configuration files.
**Current version:**
**Changed version:**

[Resolves #1042] Optimize Sceptre Start Time by only Processing Dependent Configuration Files

---

sceptre/config/reader.py

I raised PR https://github.com/Sceptre/sceptre/pull/1043 one month ago and my team and I have been testing this change internally since then. We have found a bug related to that change in the Windows environment.
```text
Do you want to launch 'dev/randc/spa' [y/N]: y
Traceback (most recent call last):
File "c:\users\heathes\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "c:\users\heathes\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\HEATHES\.local\bin\sceptre.exe\__main__.py", line 7, in <module>
File "c:\users\heathes\.local\pipx\venvs\sceptre\lib\site-packages\click\core.py", line 829, in __call__
return self.main(*args, **kwargs) …
```

[Resolves #1042] Fix Dependency Path Resolution

---

.pre-commit-config.yaml

This resolves "ImportError: cannot import name 'networkx' from 'networkx'"
seen when running the linter.

Update cfn-lint to v0.52.0

---

docs/_source/docs/resolvers.rst
setup.py

This includes the sceptre-resolver-cmd
(https://github.com/Sceptre/sceptre-resolver-cmd) into Sceptre as
a core resolver.
depends on https://github.com/Sceptre/sceptre-resolver-cmd/pull/5

Include the sceptre-resolver-cmd

---

Dockerfile

Sceptre ver 2.6.1 introduced the sceptre-cmd-resolver as a core resolver
however it looks like the setup.py command to install sceptre in the
dockerfile does not seem to install that dependency.
The pip command will install sceptre with dependencies so we switch to
install sceptre with pip.

[Resolves #1072] replace setup.py with pip

---

docs/_source/docs/stack_group_config.rst
tests/test_cli.py

As requested by Khai Do, this patch adds:
- Documentation updates in stack_group_config.rst to clarify the legacy
behaviour of merging dictionaries from successive variable files.
- A test case in test_cli.py to demonstrate that behaviour.
This PR relates to open PR:
https://github.com/Sceptre/sceptre/pull/928

Documents and test updates

---

docs/_source/docs/faq.rst
docs/_source/docs/stack_group_config.rst
sceptre/config/reader.py
sceptre/stack.py
sceptre/template.py
tests/test_actions.py
tests/test_template.py

This PR adds support for configuring the Jinja2 Environment.
`j2_environment` can be defined within a stack config and is passed to [jinja2.Environment](https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.Environment).
E.g
```yaml
j2_environment:
extensions:
- jinja2.ext.i18n
- jinja2.ext.do
lstrip_blocks: True 
```
- [] The PR relates to _only_ one subject with a clear title.

[Resolve #966] Add support for J2 Environment configuration

---

README.md
docs/_source/docs/cli.rst
docs/_source/docs/stack_group_config.rst
sceptre/cli/__init__.py
sceptre/cli/helpers.py
tests/test_cli.py

Adds CLI option --merge-keys. Dictionaries in multiple var files are
merged instead of overwritten. Test cases added.
I have added flake8 noqa in `sceptre/cli/__init__.py` to avoid C901 code
complexity in the cli function.

[Resolves #919] Add merge_keys option

---

integration-tests/features/create-stack.feature
integration-tests/sceptre-project/config/12/1/2/3/C.yaml
integration-tests/sceptre-project/config/12/1/2/3/config.yaml
integration-tests/sceptre-project/config/12/1/2/B.yaml
integration-tests/sceptre-project/config/12/1/2/config.yaml
integration-tests/sceptre-project/config/12/1/A.yaml
integration-tests/sceptre-project/config/12/1/config.yaml
integration-tests/steps/stacks.py
sceptre/config/reader.py
tests/test_config_reader.py

This PR fixes nested `config.yaml` jinja substitutions (e.g `{{ someKey }}`).
Fixes issue: https://github.com/Sceptre/sceptre/issues/813
Currently, when the project structure has multiple nested config files and one of them tries to use a property from another config file sometimes works, and sometimes not, when not work the error message is `<prop> is undefined.`.
Example structure:
```text
root/
config/
prod/
A.yaml
config.yaml
2/
B.yaml
config.yaml
3/
C.yaml
config.yaml
```
`config/prod/config.yaml`
```yaml
keyA: A
```
`config/prod/2/config.yaml`
```yaml
keyB: {{ keyA }}-B
```
`config/prod/2/3/config.yaml`
```yaml
keyA: {{ keyB }}-C
```
`keyB` should render the value `A-B` and `keyC` should render the value `A-B-C`
When running `sceptre launch prod` command the `ConfigReader` class …

[Resolves #813] Fix nested config Jinja render

---

integration-tests/steps/templates.py
sceptre/template.py

The imp.py library has been deprecated since ver 3.4 in favor of
importlib[1]. This updates to using importlib.
[1] https://docs.python.org/3/library/imp.html

[Resolves #582] update imp to importlib

---

CONTRIBUTING.md
docs/_source/about.rst
setup.py

As per #1100, there are a number of `github.com/cloudreach/` URLs in this repo. To be correct, they should be `github.com/Sceptre/`.

[Resolves #1100] Fix github.com URLs

---

sceptre/cli/list.py
sceptre/plan/actions.py
tests/test_actions.py

This adds feature list change-sets -U, --url. This boolean flag if
passed causes the output of list change-sets to display a URL to the AWS
Console for that change-set rather than the change-set details
themselves as a convenience.

[Resolves #1064] Add feature list change-set --url

---

docs/_source/docs/hooks.rst

The example documentation for creating custom hooks lists that ConnectionManager is a kwarg. But that's not true. 

[Resolve #1102] Removing nonexistant parameter from documented Custom Hook

---

docs/_source/docs/templates.rst
setup.py

Scepter supports the deployment of troposphere templates however the
troposphere library does not get installed on a sceptre install because
the library dependency is not setup. This means that troposphere must
be installed separately from sceptre in order to use it. The problem
with that is that users may install a version of troposphere that may
not work with sceptre. To fix this issue I think we should add a versioned
troposphere dependency to sceptre so that users will get a version that
is tested and will most likey work with the installed version of scepter.

[Resolves #1090] Install troposphere as an extra package

---

integration-tests/features/execute-change-set.feature
integration-tests/steps/stacks.py
sceptre/plan/actions.py
tests/test_actions.py

This resolves issue #1096. SAM Templates result in a different failure message when a change set is created with no actual changes. Currently Spectre handles the same situation for _normal_ CloudFormation change sets, but it blows up if there's a SAM template since the StatusReason is a little different.

[Resolve #1096] Gracefully executing SAM Change sets

---

docs/_source/docs/stack_config.rst

This PR fixes a number of stack_output and stack_output_external examples that were highlighted in #556

[Resolves 556] fix incorrect stack_output and stack_output_external examples

---

requirements/prod.txt
setup.py

When attempting to deploy troposphere template I get the following error
```
AttributeError: 'Template' object has no attribute 'to_yaml'
```
Accoring to https://github.com/cloudtools/troposphere/issues/759  it
seems like we need to update trophoshere to a version where the
`to_yaml` was added back.  The current dependency to trophosphere (v2.0.2)
is pretty old anyways so we are updating the version to the latest 2.x
release
The latest version is 3.0.3 however updating to 3.x causes sceptre unit
tests to fail so we are sticking to the latest 2.x version.

Update troposphere library

---

.gitignore
sceptre/config/reader.py
tests/test_config_reader.py

This resolves issue #946 by solving the issue of inherited dependencies. Turns out, the problem was just a small bug with inherited objects in memory.
There was a small bug in the ConfigReader that has to do with the way list-joining works on individual stacks and how dependencies are resolved.
The basic situation was this:
* Sceptre uses the "list_join" strategy to combine StackGroup dependencies with Stack dependencies. 
* The list_join strategy creates a NEW list by combining A + B... **but only if both A and B exist**. 
* In the case where the StackGroup dependencies exist _but there are no Stack dependencies_, Sceptre just selects A and passes each stack in that group the exact same dependencies list (i.e. **same object in memory**) from the StackGroup
* The process of resolving …

[RESOLVE #946] Fixing bug preventing StackGroup dependencies

---

sceptre/plan/actions.py
tests/test_actions.py

"create" command returns 1 if stack exists while it should return 0.
It happens, due to invalud return valid in actions.py and that is not recognized as a successful stack state
(https://github.com/Sceptre/sceptre/blob/master/sceptre/cli/create.py#L48 validates is all stacks are finished with "complete" status, while create commands returns capitalized "COMPLETE")

[Resolve Sceptre#1143] "create" command existing stack handling fix

---

sceptre/config/reader.py
sceptre/template_handlers/file.py
tests/test_config_reader.py

This resolves a bug introduced in 5c0ab39. 
In the case of `--dir`, the `File` handler class's `handle` method has
received a path relative to the `project_path` due to the previously
incorrectly-named method in the `ConfigReader` class
`_get_absolute_template_path` returning the relative path.
This patch renames the incorrectly-named method
`_get_absolute_template_path` as `_get_relative_template_path` and
corrects the logic in the `File` class's `handle` method.

[Resolves #1148] Correct path logic

---

sceptre/template_handlers/file.py
tests/test_template_handlers/test_file.py

In 0abe66966bc1bd86df3884389a61edc675a8f98c, some unnecessary
refactoring occurred while fixing Issue #1148. This reverts that
refactoring and adds unit tests for the File handler.

Refactor template handler

---

sceptre/diffing/stack_differ.py
sceptre/plan/actions.py
tests/test_actions.py
tests/test_diffing/test_stack_differ.py

Some testing on the recent diff command made a couple things evident:
* The way we were generating the placeholder values for sceptre_user_data was not fully safe for rendering templates. A safer approach is to only use alphanumeric values.
* When retrieving a local template summary, if the template is invalid (such as invalid yaml or having invalid characters), we were currently interpreting that as the stack not existing... which wasn't true. This would happen specifically when getting a template summary for the LOCALLY generated template, so that didn't make sense.

[Resolve #683] Fixing diff command to handle (and not create) invalid templates

---

integration-tests/steps/helpers.py
sceptre/config/strategies.py
sceptre/resolvers/__init__.py
sceptre/stack.py
tests/test_resolvers/test_resolver.py
tests/test_stack.py

This is the first in a series of pull requests that addresses #1114 , allowing Sceptre to manage its own dependencies.
* **ResolvableProperty is refactored into a base class with a single subclass (for now): ResolvableContainerProperty.** _This refactor will be necessary so we can build on that base class to make a ResolvableValueProperty in a later PR so we can resolve single values like template_bucket_name, etc..._. 
* **The merge strategies list_join and dict_merge now perform deepcopy on the product of those joins,** preventing changes in child stack configs from modifying the same dict/list in memory that has been inherited by other child stack configs. This change is necessary so inheriting mutable values from parent configs becomes a lot safer.
* **A few bugs have been fixed in …

[Resolve #1114,#426] Project Dependencies part 1: ResolvableProperty refactor + tags resolvable property

---

requirements/prod.txt
setup.py

See #1175 for more information, but the bottom line is that the lack of comma in our setup file is triggering a cascade of DeprecationWarnings when using the latest version of Sceptre.

[Resolve #1175] Adding commas for cfn-flip dependency

---

docs/_source/docs/permissions.rst
docs/_source/docs/stack_config.rst
docs/_source/docs/stack_group_config.rst
docs/_source/index.rst
integration-tests/sceptre-project/config/project-deps/dependencies/assumed-role.yaml
integration-tests/sceptre-project/config/project-deps/main-project/config.yaml
integration-tests/sceptre-project/templates/project-dependencies/assumed-role.yaml
sceptre/connection_manager.py
sceptre/stack.py
tests/test_stack.py

This is the third in a series of pull requests that addresses #1114 , allowing Sceptre to manage its own dependencies.
* iam_role becomes a resolvable property
* The temporary circular dependency that happens when a resolving an iam_role requires using the iam_role is handled gracefully.
* Integration tests and docs to clarify the resolvability of the IAM role are added.

[Resolve #1114] Project Dependencies part 3: Resolvable iam_role

---

docs/_source/docs/terminology.rst

This change corrects a spelling error in the Terminology section of the documentation.

[Resolves #1194] Docs: "know"->"knows"

---

docs/_source/docs/get_started.rst

Resovles #1197 
The default path for templates is already `templates` directory. This causes `sceptre create dev/vpc.yaml` command to fail with  the error message below.
```
FileNotFoundError: [Errno 2] No such file or directory: '.../templates/templates/vpc.yaml'
```

[Resolve #1197] docs: fix template path in getting-started

---

docs/_source/docs/stack_group_config.rst

The documentation stated that keys are available via stack_group_confg. When using stack_group_confg to access keys an error occurs on the validation. When using stack_group_config the validation and deployments of configurations work.

Fix spelling of stack_group_config in documentation

---

sceptre/diffing/stack_differ.py
tests/test_diffing/test_stack_differ.py

This handles cases with trailing linebreaks being passed to parameters. While this normally doesn't happen when using yaml,  it's very likely when using the !file_contents resolver. This fixes the issue to avoid false-diffs.

[Resolve #1218] Fixing false-diff reports when parameters end with linebreaks

---

requirements/prod.txt
setup.py
tests/fixtures-vpc/templates/compiled_vpc.json
tests/fixtures-vpc/templates/compiled_vpc_sud.json
tests/fixtures-vpc/templates/vpc.json
tests/fixtures-vpc/templates/vpc.template
tests/fixtures/templates/compiled_vpc.json
tests/fixtures/templates/compiled_vpc_sud.json
tests/fixtures/templates/vpc.template
tests/fixtures/templates/vpc.without_start_marker.yaml
tests/fixtures/templates/vpc.yaml

On python 3.10 pip fails when installing troposphere.
The troposphere library needs to be updated to support
python 3.10.  It's also pretty old and should be updated
anyways.  This is partial resolution for issue #1225
```
Collecting troposphere<3,>=2.7
Using cached troposphere-2.7.1.tar.gz (205 kB)
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [12 lines of output]
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 14, in <module>
File "/Users/zaro0508/.pyenv/versions/3.10.1/envs/py310-sceptretest1/lib/python3.10/site-packages/setuptools/__init__.py", line 20, in <module>
from setuptools.dist import Distribution, Feature
File …
```

update trophosphere version

---

.circleci/config.yml
Makefile

Unit tests are taking a long time to run.  Change tox to run
them in parallel[1] to speed up the test execution.
[1] https://tox.wiki/en/latest/example/basic.html#parallel-mode

Make unit tests run in parallel

---

.circleci/config.yml

The CI workflow does not need the AWS CLI.

CI does not need awscli

---

.circleci/config.yml

Setup the circleci cache and workspace settings to speed
up sceptre build and tests pipelines.
* reduce the build pipeline time from ~5 min to 1 min
* reduce the lint-and-unit-tests pipeline from ~6 min to ~3 mins

use circleci cache to speed up builds

---

sceptre/config/reader.py
sceptre/template.py

The purpose of this change is to get us to a point where we can add
support for python 3.10.  It partially resolves issue #1225 
* pkg_resources does not work with python 3.10 so need to switch
to importlib.
* importlib entry_points requires keyword arguments in python 3.10

Update sceptre to use importlib

---

sceptre/cli/drift.py
sceptre/plan/actions.py
tests/test_actions.py

Adds a feature --drifted to drift show to filter out IN_SYNC
resources.

[Resolve #1224] Add --drifted option to drift show command

---

sceptre/cli/helpers.py

Before this, an empty var file would cause sceptre to fail with an
exception
```
TypeError: 'NoneType' object is not iterable
```
This was caused by yaml.safe_load returning `None` instead of an empty
dict. This adds a default value to avoid this bug.

[Resolve #1234] Bugfix in helpers.py

---

.circleci/config.yml
.pre-commit-config.yaml
README.md

Deploy sceptre docker images to dockerhub sceptreorg repo instead of cloudreach repo
depends on https://github.com/Sceptre/sceptre-circleci/pull/16

[Resolves 1098] Deploy docker container to sceptreorg repo

---

sceptre/helpers.py
sceptre/plan/actions.py
tests/test_actions.py
tests/test_helpers.py

Resolves #1273 by starting event filtering from the timestamp returned in the AWS response headers rather than relying on the workstation clock.

[Resolve #1273]: Events start from response time

---

sceptre/template_handlers/http.py
tests/test_template_handlers/test_http.py

This PR addresses #1253 by throwing an informative error when the template fails to download instead of passing the error message to CloudFormation.

[Resolve #1253]: Failed downloads in http handler now raise exceptions

---

.circleci/config.yml

Update to build and test with a docker image that's based on the official circleci python docker image.
depends on https://github.com/Sceptre/sceptre-circleci/pull/18

Update sceptre-circleci docker image

---

docs/_source/docs/stack_config.rst
sceptre/cli/create.py
sceptre/cli/delete.py
sceptre/cli/describe.py
sceptre/cli/diff.py
sceptre/cli/drift.py
sceptre/cli/dump.py
sceptre/cli/execute.py
sceptre/cli/launch.py
sceptre/cli/list.py
sceptre/cli/policy.py
sceptre/cli/prune.py
sceptre/cli/status.py
sceptre/cli/template.py
sceptre/cli/update.py
sceptre/config/reader.py
sceptre/context.py
sceptre/plan/actions.py
sceptre/stack.py
tests/test_actions.py
tests/test_config_reader.py
tests/test_context.py
tests/test_stack.py

Allow user to disable a cloudformation rollback on a Sceptre deployment.

[Resolves #1179] cloudformation disable-rollback option

---

sceptre/cli/launch.py

We want the default value to be None to represent "Do whatever's configured in the StackConfig" and True/False will override the StackConfig. This is how the option is defined in the other files so I think this instance just slipped through the cracks in #1282.

[Resolves #1179] Changed disable-rollback default to None

---

docs/_source/docs/faq.rst
docs/_source/docs/hooks.rst
docs/_source/docs/resolvers.rst
docs/_source/docs/template_handlers.rst
pyproject.toml
sceptre/connection_manager.py
sceptre/hooks/cmd.py
tests/test_connection_manager.py
tests/test_hooks/test_cmd.py

When developing custom hooks, resolvers, and template_handlers, it is often necessary to invoke AWS services. The _correct_ way to do this is via the stack's ConnectionManager so that they can work according to the project and stack configurations for AWS connections (particularly with regard to the profile, region, and iam_role).
I consider the ease of developing custom hooks, resolvers, and template_handlers one of Sceptre's great strengths that distinguishes it from other competing utilities. However, over my time developing these custom extensions, it has not often been straight-forward to invoke AWS services. I've noticed a few ugly bits that I have only been able to make work because of my fairly deep knowledge of the inner workings of Sceptre:
* There isn't really any documentation …

Making the ConnectionManager a more "friendly" interface for hooks, resolvers, and template handlers

---

sceptre/config/reader.py

Improves the stack config Jinja syntax error message to include the stack name.
```
expected token 'end of print statement', got 'bar'
```
```
dev/stack.yaml - expected token 'end of print statement', got 'bar'
```
- Resolves #1293

[Resolve #1293] Improve the Stack Config Jinja Syntax Error Message to include the Stack Name

---

sceptre/cli/__init__.py

It turns out we had a line that showed EVERY instance of DeprecationWarning in the CLI root function. But this mixed VERY POORLY with the deprecation warnings we were emitting. If there were 30 uses of a deprecated field, it would emit 30 identical warnings.
This fixes the issue.

Preventing duplicate deprecation warnings

---

sceptre/connection_manager.py
tests/test_connection_manager.py

For a complete description on the situation that we need to resolve, see issue #1299.
This PR updates the logic on the `call()` method (the primary public method on ConnectionManager) to make it operate with fewer "gotchyas" involved. See the docstring and extensive comments within the body of the function for more explicit details, but here's the general TLDR of this change:
* `profile`, `region`, and `sceptre_role` parameters all default now to a special STACK_DEFAULT constant, which means "use the default configuration of the targeted stack". _When `stack_name` is `None`_, this means it will use the default configuration for these values for the CURRENT Stack; _When the `stack_name` is NOT `None`_, this means it will use the default configuration for the _named_ stack.
* When any one …

[Resolve #1299] Making ConnectionManager.call() work the way we all want it to

---

CHANGELOG.md
sceptre/__init__.py
setup.cfg

This releases the changelog for v4.0.0 (and 3.3)

Releasing v4.0.0

---

CHANGELOG.md
sceptre/__init__.py
setup.cfg

- Supporting `!rcmd` resolver up to v2

Releasing v4.0.1

---

sceptre/resolvers/stack_output.py

This PR caches the stack outputs of each cache so that we're not making redundant requests for the same stack outputs over and over again (which is what we currently do now in every instance we use !stack_output or !stack_output_external).
Thanks to @dboitnot for the very simple solution suggestion!
(I've not written any tests because I believe that if existing unit and integration tests pass, this should be considered very "safe".)

[Resolve #1263] Stack output caching

---

sceptre/config/reader.py
sceptre/plan/actions.py
sceptre/plan/plan.py
sceptre/stack.py
tests/test_config_reader.py

After it was discovered that ConfigReader.read() is a private method, an alternative implementation of dump config is proposed.
Here, we make the following changes:
- Add an attribute `config` to the Stack class which receives the config from the reader.
- The dump config action in the plan is updated to simply return the config attribute.
- For clarify, the read method in ConfigReader is renamed _read to make it clearer that this is a private method.

[Resolve #1324] Reimplement dump config

---

sceptre/stack_status_colourer.py

Add colouring for missing state DELETE_SKIPPED
I use colour cyan because it appears that this is not a real state but shows up sometimes anyway e.g. when updating a SAM stack that contains a Lambda Layer Version.

Add colouring for missing state DELETE_SKIPPED

---

sceptre/diffing/stack_differ.py
tests/test_diffing/test_stack_differ.py

In the case of a parameter dictionary that contains nulls (None) the Boto3 library has been found to take care of converting None to "". This means that launching such a stack in CloudFormation with a parameter dict containing params set to None works fine, whereas this differ raised an exception when it tried to strip newlines.
This patch stops newlines being stripped in the case of a parameter that is set to None.

[Resolve #1336] Add bugfix in Stack Differ

---

docs/_source/docs/hooks.rst
sceptre/cli/dump.py
sceptre/cli/template.py
sceptre/diffing/stack_differ.py
sceptre/hooks/__init__.py
sceptre/plan/actions.py
sceptre/plan/plan.py
tests/test_diffing/test_stack_differ.py
tests/test_hooks/test_hooks.py
tests/test_plan.py

This addresses the current issue raised in #1344. 
Here is what this includes:
* The `dump_template` action ALSO triggers `before_generate` and `after_generate`
* The `generate` action ALSO triggers `before_dump_template` and `after_dump_template`
* The StackDiffer invokes `dump_template` rather than `generate`, preventing our own code from triggering deprecation warnings.
* The documentation for hook points is updated to include all current hooks, including notes about the aliasing.
* Deprecation of `generate` is removed after discussion in Slack. This deprecation would be too disruptive to many users, and we agreed instead to support a permanent alias of `generate` => `dump_template`.
[Guide to writing a good …

[Resolve #1344] Addressing issue with Generate hook and its deprecation

---

CHANGELOG.md
pyproject.toml

- [Resolve #1344] Addressing issue with Generate hook and its deprecation (#1346)
Here is what this includes:
* The `dump_template` action ALSO triggers `before_generate` and
`after_generate`
* The `generate` action ALSO triggers `before_dump_template` and
`after_dump_template`
* The StackDiffer invokes `dump_template` rather than `generate`, preventing
our own code from triggering deprecation warnings.
* The documentation for hook points is updated to include all current hooks,
including notes about the aliasing.
* Deprecation of `generate` is removed after discussion in Slack. This
deprecation would be too disruptive to many users, and we agreed instead
to support a permanent alias of `generate` => `dump_template`.

Release v4.2.1

---

.pre-commit-config.yaml
CHANGELOG.md
Dockerfile
requirements/prod.txt
sceptre/__init__.py
setup.cfg
setup.py

Make the 3.2.x release buildable again to prepare
for a patch release.
* pre-commit linters were failing so update them to work
* update libraries and docker version to fix the cython issue

[Resolves #1358] Fix installer for version 3.2

---

integration-tests/steps/stacks.py
requirements/prod.txt
sceptre/__init__.py
setup.cfg
setup.py

There is a fix for PyYaml post ver 6.0.  Update dependency to pick up the fix.

[Resolve #1358] update PyYaml dependency

---

sceptre/plan/actions.py
tests/test_actions.py

[Resolve #1343] Add feature to print out CloudFormation hook status to Sceptre output when logging new stack events
This pull request brings the ability for Sceptre to print out CloudFormation hook status when logging new stack events. They are "HookType","HookStatus","HookStatusReason" and "HookFailureMode". The information facilitates early picking up of CloudFormation hook issues/failures.
Added CloudFormation hook information to `_log_new_events` method in `sceptre/plan/actions.py` module and its matching unit tests in `tests/test_actions.py` module.
More details and discussion please refer [Ability to show the cloudformation hook status and message in the sceptre output #1343](https://github.com/Sceptre/sceptre/issues/1343) and [1343 logging hook status …

[Resolve #1343]  Add feature to print out CloudFormation hook status to Sceptre output when logging new stack events

---

docs/_source/docs/hooks.rst
sceptre/hooks/cmd.py
tests/test_hooks/test_cmd.py

The cmd hook now accepts named arguments `run` and `shell` to run a command in a
given shell. For backwards compatibility it still supports the unnamed
argument to run a command in the default shell.
The documentation shows the expected output for examples of each argument style.
The unit tests no longer depend on the implementation of Cmd and test only the
behavior. This makes it easier to change how the hook controls the subprocess.

[Resolves #1213] Add shell option to cmd hook

---

tests/test_hooks/test_cmd.py

The old test expected `/bin/sh` to write Dash's error message. This works on
Ubuntu 20.
It old test failed  when `/bin/sh` pointed to `/bin/bash`. This happens on
macOS.
The new test no longer depends on system-defined side effects of a missing
command. It just writes to the standard error stream and checks that the same
text comes out.

[Resolves #1383] Simplify stderr test for cmd hook

---

.circleci/config.yml
.flake8
poetry.lock
pyproject.toml
sceptre/stack.py
tox.ini

Update circleci docker container with python 3.7 removed and python 3.12 added
depends on https://github.com/Sceptre/sceptre-circleci/pull/19

Update docker container for CI

---

docs/_source/docs/stack_config.rst
docs/_source/docs/template_handlers.rst
integration-tests/steps/templates.py
sceptre/config/reader.py
sceptre/stack.py
tests/fixtures/config/account/stack-group/region/vpc.yaml
tests/fixtures/config/top/level.yaml
tests/test_actions.py
tests/test_config_reader.py
tests/test_stack.py

This reverts commit bc828dc70a9e970f5294d7eb76f6a259dfc47bf7. The `template_path` removal should go out on a major release because it's a breaking change.   However we are not ready for a major release yet.  Temporarily revert this change.

Revert "Remove template_path config parameter (#1386)"

---

CHANGELOG.md
pyproject.toml

Prep for a release to support python 3.12
Updates to our plugins[1] depend on a Sceptre core release with support for python 3.12 [2]
[1] PR https://github.com/Sceptre/sceptre-file-resolver/pull/12#issuecomment-1865415871
[2] PR https://github.com/Sceptre/sceptre/pull/1390

bump version and update Changelog for release

---

.circleci/config.yml

*  Changed to publish using the API token instead of user authentication.  Got the following error when attempting to publish to pypi.
```
403 Username/Password authentication is no longer supported. Migrate to
API Tokens or Trusted Publishers instead. See https://pypi.org/help/#apitoken and
https://pypi.org/help/#trusted-publishers. Access was denied to this resource
```
* publish to pypi test was not executing.  fix so that it runs
as part of the test job in CI.

Pushlish using pypi api token

---

.circleci/config.yml

publishing to test.pypi should not be in the CI because pypi only allows one unique version number to be published.  It's strictly for manually testing deployments to pypi

Remove deploy to pypi test in CI

---

.github/workflows/main.yaml

The docker metadata action returns the branch (i.e. `master`) when a
push occurs. That causes docker push to fail because there's not master
tag in the registry.  We need to change to make it push to `latest`
tag in dockerhub registry.

fix deployment to dockerhub

---

.github/workflows/main.yaml

* The integration tests were failing because it wasn't being run against the eu-west region.  The CONTRIBUTING.md[1] docs clearly state the the tests are setup to run in eu-west-* region.
* Update the CI workflow to trigger integration tests only after all other tests have completed and passed.
* Trigger build on any branch to allow admins to trigger an integration-tests job when pushing branches.
* Update docker tags.  I've heard that the docker convention for tags is `latest` tag refers to the latest stable release and `edge` tag refers to the latest code. 
[1] https://github.com/Sceptre/sceptre/blob/master/CONTRIBUTING.md#integration-tests

Fix integration tests

---

.github/workflows/main.yaml

use `github.event_name` instead of `github.ref_type` to identify the github event.

CI: fix github event reference

---

integration-tests/features/stack-output-external-resolver.feature
integration-tests/sceptre-project/config/external-stack-output/resolver-with-profile-region.yaml

An AWS profile was used to run integration tests in circleci.  We have moved to github actions and we've also moved to using GH OIDC instead of an AWS profile.  A test that validates the use of a profile was passing in circleci but is now failing in GH actions.  Since we no longer use a profile we cannot run tests to validate the usage of profiles therefore it has been removed.

Remove an external resolver integration test

---

.github/workflows/main.yaml

CI jobs that build python packages do not require a step to install poetry dependencies

CI: Remove install dependencies step

---

.github/workflows/comment-integration-tests.yaml
.github/workflows/gate.yaml
.github/workflows/integration-tests.yaml

Setup a workflow to trigger an integration test run from a review comment.
Integration tests take a long time to complete therefore it is typically only run as a final check before merging to the master branch.
The idea is to allow users to trigger an integration test run only after all other tests have passed AND a human review approval has been provided. Adding an `/integration-tests` string to a PR review will trigger the integration test run.

CI: add integration test workflow

---

.github/workflows/branch-integration-tests.yaml
.github/workflows/gate.yaml

The integration tests is triggered twice on force pushes to master. We only want it to run once.
* trigger integration tests on merges to master branch
* trigger integration tests on creation of branches from PRs
* do not trigger integration tests twice

stop duplicate gate workflow runs

---

pyproject.toml

Removing classifiers in poetry.toml because poetry will auto generate the classifiers[1]
[1] https://python-poetry.org/docs/pyproject/#classifiers

Remove classifiers

---

sceptre/stack.py
tests/test_stack.py

For historical reasons, Sceptre has never validated Stack config [parameters](https://docs.sceptre-project.org/latest/docs/stack_config.html#parameters) that are passed in to CloudFormation stack parameters. Blocks that contain bools, ints etc give rise to confusing failures. For example:
```yaml
parameters:
someBool: true
```
Would lead to an error appearing like:
```
"Parameter validation failed:\nInvalid type for parameter Parameters[0].ParameterValue, value: 1, type: <class 'bool'>, valid types: <class 'str'>"  
```
In more complicated examples it is often quite unclear what Parameter[0] means.
A feature here is added at the time of Stack instantiation to perform validation of the input stack parameters in a similar manner to how the ignore and obsolete settings were already being …

[Resolve #1443] Add parameter type checking

---

sceptre/config/graph.py

This adds some code to print a clearer error message similar to Terraform's when a cyclical dependency is detected in the graph.
Before this change an error message would look like:
```
Dependency cycle detected: configmap-lambda eks-securitygroups
```
After this change it becomes:
```
Dependency cycle detected: eks-securitygroups -> configmap-lambda, configmap-lambda -> eks-securitygroups
```
An example of a Terraform error message would be:
```
Error: Cycle: aws_scheduler_schedule.gh_runners_ubuntu_stop, aws_iam_role.gh_runners_ubuntu_scheduler_role, aws_scheduler_schedule.gh_runners_ubuntu_start
```
And for comparison see this related section of the source code for Terraform:
https://github.com/hashicorp/terraform/blob/268c8e264d22604f2a4ec516ed4df7a5bdef421f/internal/dag/dag.go#L117-L1 …

[Resolve #1446] Print edges in cyclical dependency

---

sceptre/diffing/stack_differ.py

Update `NO_ECHO_REPLACEMENT` to remove some false positives when calling `sceptre diff` on stacks containing parameters with `NoEcho: True`.

[Resolves #1460] Update `NO_ECHO_REPLACEMENT`

---

.pre-commit-config.yaml
README.md

The pre-commit bot added 906005d36c9b773894c075203b898f42988e229f which broke the build. Root cause is the lastest version of the CFN Lint emits errors about some of the integration test CloudFormation code. This tweaks the linter config to ignore these files. 

Fix broken build caused by pre-commit bot

---

sceptre/stack.py
tests/test_stack.py

This adds logic to `_cast_parameters` to also handle the case that the `parameters` dict itself is not a dict but some other invalid type.

[Resolve #1484] Gracefully handle invalid parameters

---

integration-tests/features/describe-change-set.feature
integration-tests/features/execute-change-set.feature
integration-tests/steps/helpers.py
sceptre/cli/helpers.py
sceptre/plan/actions.py

This adds code to handle the case of failures in stack groups that have missing or errored stacks when creating, describing and executing change-sets.
Before this, any stack group that contained a stack that had been deleted, or had errored out, resulted in all change set operations on that stack group failing.
The reason for this is no error or exception handling had ever been added for change sets, but assumed all stacks in the stack group were clean and could respond to the change set APIs.
For example, deleting change sets might error out with:
```
% sceptre delete -y network.yaml sceptre-network
The Change Set will be delete on the following stacks, if applicable:
network
"An error occurred (ValidationError) when calling the DeleteChangeSet
operation: Stack [test-e2e-direct-connect] …
```

[Resolve #1483] Handle errors in change sets

---

sceptre/cli/update.py
sceptre/plan/actions.py
tests/test_actions.py

This adds missing code to complete the implementation of the DisableRollback feature.
The implementation in 99c839a2b began this feature by adding disable rollback to the create and update CLI commands, but it was forgotten to update the stack actions. 
This adds the missing code and another unit test.

[Resolve #1493] Complete DisableRollback implementation

---

sceptre/stack.py

Way back in 2018, the original team were adding the debug command, and in that context set about to improve the output in some debug circumstances during inspection of Sceptre's internal objects.
In response to https://github.com/Sceptre/sceptre/issues/570, a custom `__eq__` method was added in df9fc201aaed59c173b11b80e804244a5b2f3bfb.
Based on what can be seen of the original implementation of the custom `__eq__`, it has not been maintained in a long time, other than changes to it that appeared forced on the current maintainers.
A recent change 993ef0937d9a49a1683feb9591c4526ee0fe29af was done to improve the output during cyclical dependency errors. This change introduced a call to `nx.find_cycle`, a function that explicitly searches for a cycle in the graph. This appears to result in …

[Resolve #1506] Remove unused __eq__ method

---

docs/_source/docs/install.rst

The official docker images have moved to a new location.

[resolves #1514] Update docs for docker repo

---

sceptre/plan/actions.py
tests/test_actions.py

Resolve https://github.com/Sceptre/sceptre/issues/1517
The Cloudformation hook logging message was bit confusing as it stated the hookmode at the end of the hook log.
The log is shown as below for the successful hook execution:
```
07:17:25  [2024-09-17 01:47:24] - sbox-01/sbucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS  sample::Generic::Megahookblock HOOK_COMPLETE_SUCCEEDED Hook succeeded with message: Hook Successfully completed **FAIL**
```
Even though the hook completed successfully, it mode mentioned at the end of the message is misleading to the end user looking into the logs.
As the failure/warn is mentioned in the hook message after the execution, removing the HOOKMODE from this log message.
Log when Hook Fails in the FAIL mode
```
07:17:33  [2024-09-17 01:47:33] - …
```

[Resolve #1517] Updated the Cloudformation Hook logging message

---

tests/test_hooks/test_cmd.py

Resolve #1520 - Replaced hard-coded shell paths

[Resolve #1520] Replace hard-coded shell paths

---

.pre-commit-config.yaml

By default pre-commit auto updates it's linters weekly[1].  This seems a big too aggressive so we are changing it to monthly.
[1] https://pre-commit.ci/#configuration-autoupdate_schedule

Update pre-commit auto update schedule

---

tox.ini

[Resolve #1539] Drop Python 3.8 support

---

poetry.lock
pyproject.toml

python v3.8 is EOL and it was dropped in PR #1540

update python requirement

---

.github/workflows/release.yaml

Docker build and push action changed, it now pushes the specified tag and `latest` tag in one command.
`--tag sceptreorg/sceptre:v4.5.3 --tag latest`
This causes the error `ERROR: denied: requested access to the resource is denied` on the 2nd push of the latest tag.

Fix docker release
