Sceptre/sceptre

docs/get_started.rst

As mentioned in https://github.com/cloudreach/sceptre/issues/15

Fix error in get started docs

---

docs/python_module.rst

Update python module docs [skip ci]

---

docs/command_line.rst

Updating CLI docs

---

docs/stack_config.rst

Fix broken link

---

docs/advanced_patterns.rst

* Changed super class call.
* Updated config example.

Fixes to custom resolver docs

---

sceptre/template.py

Fix exception formatting

---

integration-tests/steps/test_change_set.py
sceptre/cli.py
tests/test_cli.py

Include Scope in update-stack-cs output

---

sceptre/cli.py
sceptre/stack.py
sceptre/template.py
tests/test_cli.py
tests/test_stack.py
tests/test_template.py

Simply renaming `cfn` to `body` in the Template class as it better defines the attribute.

Rename cfn attribute of Template to body

---

sceptre/environment.py
tests/test_environment.py

Rename _get_stack_statuses to _get_initial_statuses

---

sceptre/cli.py

Improve update-stack-cs docstring

---

sceptre/template.py
tests/test_template.py

Refactored the upload_to_s3 and create_bucket function in Template class. Introduced a bucket_exists function to encapsulate some the create_bucket logic.

Refactor upload to s3

---

README.rst
docs/installation.rst

Update installation docs [skip-ci]

---

docs/advanced_patterns.rst

Updated documentation to reflect the structure required for hooks.

fix documentation for hook configuration

---

tests/test_hooks/test_asg_scaling_processes.py

This is hotfix - as master not passing lint test due to PR #88

Update hook test name to pass linting

---

README.rst

Fixing a few URLs in README

---

docs/docs/resolvers.md
docs/docs/templates.md

* Fix whitespace on example resolver code
* Fix escaping on example for jinja templating

documenation fixes

---

docs/docs/stack_config.md
integration-tests/features/create-stack.feature
integration-tests/sceptre-project/config/8/A.yaml
integration-tests/sceptre-project/config/8/B.yaml
integration-tests/sceptre-project/config/8/config.yaml
integration-tests/sceptre-project/config/config.yaml

This further adding documentation and integration tests for the on_failure parameter added to stack configs.

On failure stack parameter documentation and integration tests

---

docs/docs/cli.md
docs/docs/stack_config.md

This PR fixes missing or improperly rendered documentation. Adding notes about the diff and init command to Sceptre cli. Fix rendering to environment_config variables available in Jinja templating of stack configs.  

Add missing documentation

---

README.rst

Added the CircleCli build status badge to the README.

added CircleCli badge to README [skip-ci]

---

.github/PULL_REQUEST_TEMPLATE.md

In light of @adispen's comments, it should be made clearer which text should be replaced for the PR summary.

Clarify what text to replace in the PR template

---

docs/docs/architecture.md

This fixes a typo in the documentation.

Fix typo in documentation

---

docs/docs/architecture.md

Fixes another typo in the architecture doc

Fix typo: s/thier/their/ in architecture doc

---

README.rst

[Resolve #312] add badges

---

Makefile

* [N/A] [Squashed related commits together][2] after the changes have been approved.
* [N/A] Added unit tests.
* [N/A] Added integration tests (if applicable).
* [N/A] All unit tests (`make test`) are passing.
* [N/A] Used the same coding conventions as the rest of the project.
* [N/A] The new code doesn't generate flake8 (`make lint`) offenses.

Document make install-dev in make help

---

Makefile
docs/Gemfile.lock
docs/Makefile
docs/README.md

Cherry picks @JuanCanham commit c58ab85b18824c9b1d8470f90649c6c13a9c8ab2  into version 1 branch. 

[Resolves #338] fix docs on viewing docs (#317)

---

contrib/README.md

Adding contrib/ & README to allow Sceptre extensions to be easily
* [n/a] Added unit tests.
* [n/a] Added integration tests (if applicable).
* [n/a] All unit tests (`make test`) are passing.

[Resolves #340] Add contrib folder

---

.circleci/config.yml

Updated circleCI config to reflect changes in documentation make file. 

[Resolves #362] Fix dev docs deploy

---

docs/docs/stack_config.md
integration-tests/features/create-stack.feature
integration-tests/features/update-stack.feature
integration-tests/sceptre-project/config/8/C.yaml
integration-tests/steps/stacks.py
sceptre/config_reader.py
sceptre/stack.py
tests/test_stack.py

Reverts cloudreach/sceptre#300

Revert "Stack_timeout config key for create and update stack"

---

integration-tests/sceptre-project/config/config.yaml
sceptre/config_reader.py
sceptre/stack.py
tests/fixtures/config/config.yaml
tests/test_config_reader.py
tests/test_stack.py

Reverts cloudreach/sceptre#348

Revert "[Resolves #330] `profile` added to stack's connection manager"

---

docs/docs/resolvers.md

Seeing as this is the documentation for resolvers, I would imagine it should say resolvers.
**Replace the text above the line with a summary of the changes in your PR.
The more detailed you are, the better. Before submitting the PR, make sure the following are checked.**
* [x ] Wrote [good commit messages][1].
* [x ] [Squashed related commits together][2] after the changes have been approved.

UPDATE resolvers.md - change hooks -> resolvers

---

sceptre/template.py
tests/fixtures/templates/vpc.template
tests/test_template.py

Cherry pick the previous commit into v1 branch.
See: https://github.com/cloudreach/sceptre/issues/350

[Resolve #254] add ".template" to file extensions

---

requirements.txt
setup.py

Cherry pick from master. Allows Jinja version upgrades for v1.

[Resolve #351] Allows jinja2 <=2.8, for upgrades (#354)

---

.circleci/config.yml

Cherry pick 62e7a5de2484c1741d003c311729309ade25f82d to v1 branch.

[Resolves #271] Decrease circleci parallel runs (#386)

---

requirements.txt
setup.py

Update Click and PyYaml dependency versions

---

HISTORY.rst

Update history for v1.4 release

---

sceptre/strategies.py

This resolves a small bug in the dictionary merging strategy.
Previously, the merge would return None in some cases.

[Resolves #464] Fix config merge strategy

---

docs/docs/cli.md

Docs: Remove the `diff` command.

Update cli.md: Remove the `diff` command.

---

setup.py

Thanks to @1oglop1 for the suggestion.

Use findpackages in setup.py

---

CONTRIBUTORS.md
README.md

This PR fixes some minor issues with the README and CONTRIBUTORS docs.
Contributors:
- Fix double @ signs before GitHub usernames and unnecessary @ sign
in the GitHub profile links
- Remove double slashes in the links
Readme:
- Fix the 'Contributing Guide' link
- Remove bash syntax coloring, as the pasted console output does not
contain any meaningful bash keywords
- Update sceptre help output to match 2.0.0rc2

[RC2] Minor documentation fixes

---

sceptre/config/graph.py

Removes write method from graph. Was useful in development but not required anymore. 

Remove graph write method

---

sceptre/config/reader.py
sceptre/stack.py
tests/fixtures-vpc/config/account/stack-group/config.yaml
tests/test_config_reader.py
tests/test_stack.py

Add `stack_group_config` to `Stack` as attribute

Add `stack_group_config` to `Stack` as attribute

---

docs/_includes/docs_navigation.html
docs/_includes/head.html
docs/about.md
docs/assets/css/sceptre.css
docs/docs/architecture.md
docs/docs/cli.md
docs/docs/faq.md
docs/docs/get_started.md
docs/docs/hooks.md
docs/docs/install.md
docs/docs/resolvers.md
docs/docs/stack_config.md
docs/docs/stack_group_config.md
docs/docs/templates.md
docs/docs/terminology.md
docs/index.html
sceptre/config/reader.py

[Resolves #306] Update docs

---

docs/docs/cli.md

This is a one-character syntax fix to documentation to improve syntax, so I've not added any tests. I also didn't bother filing an issue for this before creating the PR.

Add newline in cli.md to format code block correctly

---

docs/docs/resolvers.md

There was a divergence between the available attributes of resolvers and
what was documented when developing v1 -> v2. This commit updates the
Sceptre website documentation so that it reflects the available
attributes in v2.

[Resolves #543] Update custom resolver docs

---

.circleci/config.yml
Makefile
docs/_config.yml
docs/docs/stack_config.md

Some small changes to various project files. 
PR does:
fix docs deployment for tagged commits,
fix jekyll deprecation warnings  
fix deprecation warning for python setup check. 

Update project config files

---

sceptre/cli/delete.py

Improves message presented to user on CLI when deleting a change set. 

[Resolves #551] Improve delete change set message

---

CHANGELOG.md
sceptre/__init__.py
setup.cfg

Update CHANGELOG and bumpversion for 2.0.1 release. 

2.0.1 Release

---

docs/docs/stack_group_config.md

This fixes a tiny typo in the documentation.

Fix documentation typo: s/peofile/profile/

---

sceptre/cli/__init__.py
sceptre/cli/helpers.py
sceptre/cli/list.py
sceptre/cli/template.py
tests/test_cli.py

Fixes issue with `sceptre.cli.helpers.write` method.

[Resolves #581] Fix `generate` command cli output

---

sceptre/plan/actions.py

Remove redundant stack.status self-assignment

---

CHANGELOG.md
CONTRIBUTORS.md
README.md
setup.py

Updates the relevant project documentation ahead of 2.0.2 release.

Update project docs for 2.0.2

---

CHANGELOG.md
CONTRIBUTORS.md
README.md
docs/docs/stack_group_config.md
requirements.txt
sceptre/__init__.py
sceptre/cli/__init__.py
sceptre/cli/helpers.py
sceptre/cli/list.py
sceptre/cli/template.py
sceptre/plan/actions.py
sceptre/stack.py
setup.cfg
setup.py
tests/test_cli.py
tests/test_stack.py
tests/test_template.py

2.0.2 Release

---

requirements.txt
setup.py

[Resolves #598] Unpin six version

---

sceptre/cli/update.py

Fix update with Change Set option

---

CONTRIBUTORS.md
docs/Gemfile.lock
docs/_api/conf.py
docs/_includes/footer.html
docs/_layouts/home.html
docs/about.md
docs/docs/cli.md
docs/docs/get_started.md
docs/docs/install.md

A number of documentation improvements and build fixes discovered while running through the Get Started guide. I'm aware that some of this (e.g. wording) is subjective and I'm definitely open to pushback on that. Tried my best to make things clearer from the perspective of a completely fresh user.
The Gemfile dependencies were updated based on warnings printed by `bundler`. I will revert if this causes problems with CircleCI.
The format of the copyright header was changed to be consistent across the entire site.
There is no issue associated with this PR. Would you like me to create one (or multiple for year automation, tutorial tidying, etc.) and amend the commit message(s)?
[Guide to writing a good …

Documentation polishing

---

sceptre/plan/plan.py

Previously, if an invalid stack path was given a `ValueError: max() arg is
an empty sequence` error was raised. This was not useful for the
end user.
This commit fixes this by assessing whether the `launch_order` list is empty
during `_generate_launch_order()` and throws a `ConfigFileNotFoundError`.
[#Resolves #575]

Improve invalid stack path error message

---

CHANGELOG.md
CONTRIBUTORS.md
docs/Gemfile.lock
docs/_api/conf.py
docs/_includes/footer.html
docs/_layouts/home.html
docs/about.md
docs/docs/cli.md
docs/docs/get_started.md
docs/docs/install.md
requirements.txt
sceptre/__init__.py
sceptre/cli/create.py
sceptre/cli/delete.py
sceptre/cli/describe.py
sceptre/cli/execute.py
sceptre/cli/helpers.py
sceptre/cli/launch.py
sceptre/cli/list.py
sceptre/cli/new.py
sceptre/cli/policy.py
sceptre/cli/status.py
sceptre/cli/template.py
sceptre/cli/update.py
sceptre/config/reader.py
sceptre/plan/plan.py
setup.cfg
setup.py

2.0.3 Release

---

requirements.txt
setup.py

Update colorama dependency version

---

sceptre/plan/actions.py

Gracefully handles stacks that don't require updating when executing `update` on a stack or stack_group

Handle stack update errors gracefully

---

.circleci/Dockerfile

Optimize CircleCI Docker Image

---

.circleci/config.yml

Change target git repository to deploy docs

---

README.md

Fix readme documentation links

---

integration-tests/steps/helpers.py
tests/test_cli.py

Update cli tests

---

docs/_source/docs/cli.rst

Improve documentation on variable handling

---

CHANGELOG.md
sceptre/__init__.py
setup.cfg

Update Changelog & Bump

---

sceptre/cli/helpers.py

Adds `Fn::Split` to the list of cloudformation functions. I've also gone through and verified that this was the only documented function that was missing.

[Resolves #767] Add missing `Fn::Split`

---

.circleci/config.yml
.gitignore
Makefile
tox.ini

Updates the project to be analysed by sonarqube. 
Required changes to CICD config and Makefile

Add sonarqube to sceptre

---

integration-tests/sceptre-project/templates/attribute_error.py

Remove code after raising AttributeError

---

sonar-project.properties

Add sonar-project properties file.

---

README.md
sonar-project.properties

Add badges sonar

---

.circleci/config.yml
.gitignore
CONTRIBUTING.md
Makefile
sonar-project.properties

Setting a fail level for tests so that we don't creep any lower!

Set test coverage fail level to 92%

---

sceptre/connection_manager.py

This adds jitter and randomness to AWS api calls.  The changes are based on the results of this article:  [Exponential Backoff And Jitter](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/). 
For context:  When doing large deploys or in general making a large amount of API calls to AWS you will hit their API limits.  AWS's preferred solution for resolving this (hitting the API limit) is to back-off with a certain level of randomness and retry. 
This fix should resolve most if not all issues with deploying a large amount of cloudformation stacks in parallel onto AWS. We have tested doing larger deploys, dozens of Cloudformation stacks, all at once and have been able to complete the deployments consistently. 
and description in grammatically correct, complete …

[Resolves #783] add random jitter to boto retry

---

sceptre/connection_manager.py

Fix lint issue

---

requirements/prod.txt

Add `typing` to prod requirements

---

setup.py

Add `typing` lib as a install dependency

---

sceptre/resolvers/__init__.py

This should fix a possible reentrancy issue.
When `Stack`s are shared between threads, and if they access their `ResolvableProperty`s, in parallel, that can lead to a data race. This is now being exposed since a recent PR makes that code crash.

[Resolve #810] Make ResolvableProperty somewhat thread-safe.

---

docs/_source/about.rst
docs/_source/docs/faq.rst
docs/_source/docs/stack_config.rst
docs/_source/docs/stack_group_config.rst

[Resolves #786] Fix broken cross-page references in doc

---

README.md
docs/_source/docs/install.rst

Clarify pip vs. Docker installation in doc

---

docs/_source/docs/cli.rst

This resolves issue https://github.com/Sceptre/sceptre/issues/802
Add documentation on how to properly run the autocomplete script
in a ZSH shell.

add autocomplete doc for ZSH shell

---

CONTRIBUTING.md

Clarify instructions on how to run integration tests locally.

update integration test instructions

---

.circleci/documentation-versions.py

Keep version 1.3.4 and 1.4.2 active on github pages

---

Dockerfile

Sorry, there was an issue with https://github.com/Sceptre/sceptre/pull/856
Raising this PR again

Upgrade to Alpine version 3.10 in Dockerfile

---

CHANGELOG.md
sceptre/__init__.py
setup.cfg

Release 2.3.0

---

README.md
docs/_source/_templates/versions.html
tests/test_cli.py

The Sceptre documentation has been moved from `sceptre.cloureach.com` to
`sceptre.github.io`.

Update documentation links to new domain

---

README.md
docs/_source/_templates/versions.html
tests/test_cli.py

This reverts commit bd7808a11738e76030698622aef6d8e399763a90.

Revert "Update documentation links to new domain"

---

requirements/dev.txt
requirements/prod.txt
setup.py

This reverts commit 319adfdfa1a6e715d1c9b29d4fadc8582c936cfe.

Revert "[Resolves #916] Bump networkx to 2.4 (#923)"

---

CHANGELOG.md
sceptre/__init__.py
setup.cfg

Release 2.4.0

---

docs/_source/docs/hooks.rst
sceptre/plan/actions.py

Add hooks to validate.
Hooks for validate are necessary for actions that are required to occur before any template validation. For example, downloading required artifacts.

[Resolve #929] Create validate hooks

---

docs/_source/docs/faq.rst

Provide examples of creating a Serverless app using SAM
with Sceptre

[Resolves #869] Update docs

---

.circleci/config.yml

Fix the sceptre build. 
* update container image to ver 0.7.0
* disable sonarqube
* disable integration tests

Fix sceptre build

---

README.md
docs/_source/about.rst

Document how to join the Sceptre Slack channel

---

docs/_source/docs/faq.rst

In order to deploy Lambda functions using either the AWS CLI
or SAM CLI we need to generate the packaged version of the
Lambda functions first. This patch details how to add the "package"
command using Sceptre hooks in a way that reuses existing Sceptre
config.yaml file information to populate the command details.

Detail how to use Sceptre hooks to deploy lambda

---

README.md

The example docker command to overrider the default entry point was incorrect.  This PR fixes that and also bumps the version image tag to `2.4.0` in a different example.

Correct docker cli example

---

.circleci/config.yml

We setup 3 separate workflows
* build-and-unit-test:  trigger on PRs (before a merge).  These jobs do not require secrets.
* build-test-and-deploy: trigger on changes to any branch. These jobs require secrets.
* tag: trigger on a tag, publishing to pypi, dockerhub, etc..  These jobs require secrets.

Setup circleci workflows

---

tests/test_cli.py

Add tests for PR #918. These tests will only pass after merging PR #918

[Resolves #881] Tests for fix to PR #918

---

requirements/dev.txt
requirements/prod.txt
setup.py

We need to update networkx, as latest versions of tools we use to work
with AWS like cfn-lint require networkx>=2.4 and the existing dependency
conflicts with such tools since it's outdated.

[Resolve #1007] Update networkx version

---

.pre-commit-config.yaml
.yamllint
integration-tests/sceptre-project/config/9/B.yaml
integration-tests/sceptre-project/templates/invalid_template.yaml
integration-tests/sceptre-project/templates/jinja/valid_template.yaml
integration-tests/sceptre-project/templates/malformed_template.yaml
integration-tests/sceptre-project/templates/sam_updated_template.yaml
integration-tests/sceptre-project/templates/valid_template.yaml
integration-tests/sceptre-project/templates/valid_template_func.yaml

Setup yamllint to validate yaml files on a pre-commit run.
[1] https://github.com/adrienverge/yamllint

add yamllint to pre-commit checks

---

.circleci/README.md

Add docs for release workflow to help maintainers remember how to make
releases

Docs for release workflow

---

requirements/prod.txt

Update library to ver > 0.4 and add upper bound.  The AWS cli uses v0.4.4

update colorama library

---

requirements/prod.txt

This reverts the update to `colorama` due to conflicts with `awscli`. I've updated the colorama requirements to match those specified by awscli.

Revert #1029 colorama

---

docs/_source/docs/resolvers.rst
setup.py

This includes the sceptre-file-resolver
(https://github.com/Sceptre/sceptre-file-resolver) into Sceptre as
a core resolver.

Include sceptre-file-resolver as a core resolver

---

integration-tests/features/delete-stack.feature
integration-tests/steps/stacks.py
sceptre/cli/delete.py
sceptre/config/reader.py
sceptre/context.py
tests/test_config_reader.py

This PR fixes issue #1078, the change applied by this PR (https://github.com/Sceptre/sceptre/pull/1043) basically change the root folder which `sceptre` scan the config files,
Before the change, `sceptre` gets from the project `config` folder causing some performance issues in large projects as described in the PR https://github.com/Sceptre/sceptre/pull/1043.
But for `delete` operation the dependency tree must be resolve in reverse mode.
**Example**:
With this project configuration:
```text
config/prod/A.yaml
config/prod/B.yaml -> depends prod/A.yaml
config/prod/C.yaml -> depends prod/B.yaml
```
When `sceptre` runs `create`, `update` or `launch` the based on the `prod/C.yaml` sceptre knows that `prod/B.yaml` is a dependency of `prod/C.yaml` explicitly because the stack is referenced …

[Resolves #1078] Fix delete CLI dependency tree

---

docs/_source/docs/stack_config.rst
docs/_source/docs/stack_group_config.rst

This adds documentation for the `iam_role` configuration to the StackGroup docs page, which was described as needed in #1107 

[Resolves #1107] Documenting the iam_role config

---

CHANGELOG.md
sceptre/__init__.py
setup.cfg

Bump version to 2.7.0

---

docs/_source/docs/faq.rst

This just updates the documentation to point users toward the new sceptre-sam-handler rather than using hooks for managing SAM with Sceptre.

Pointing SAM docs toward the sceptre-sam-handler

---

README.md
docs/_source/_templates/versions.html
tests/test_cli.py

Updating links in docs and elsewhere to new domain

Resolve #1163 update doc link to new domain

---

CHANGELOG.md
sceptre/__init__.py
setup.cfg

Bump version to 2.7.1 and update CHANGELOG

---

CHANGELOG.md

Fix up CHANGELOG.md

---

CHANGELOG.md
sceptre/__init__.py
setup.cfg

Preparing for Sceptre 3.1.0 release

Sceptre v3.1.0 Release Details

---

.circleci/config.yml

Make CI use the latest circle-ci docker image updated to alpine v3.16
with python v3.10 and pyenv pre-installed.

update sceptre-circleci docker image

---

.circleci/config.yml
CONTRIBUTING.md
setup.py
tox.ini

Run tests against python 3.10
depends on #1240

[Resolves #1225] Support python 3.10

---

requirements/dev.txt

Upgrade setuptools for build failure.

[Resolve #1245] Upgrade setuptools for build failure

---

CHANGELOG.md
sceptre/__init__.py
setup.cfg

Releasing v3.2.0

---

.circleci/config.yml
README.md

Adding the ability to tweet Sceptre releases through CircleCI.
Signed-off-by: Erica Brauer <ericabrauer1@gmail.com>

Add tweet-release to CircleCI config

---

sceptre/cli/diff.py
sceptre/diffing/diff_writer.py
tests/test_diffing/test_diff_writer.py

Implements coloured diffs for the diff command. Responds to `--no-color`.

[Resolves #1261] Add coloured differ

---

sceptre/stack_status_colourer.py

This extends the stack_status_colourer to include the 'IMPORT' related states.

[Resolves #1271] Extend stack status colourer

---

requirements/dev.txt

This combines the changes from #1280 and #1281. I couldn't get integration tests to run on those PRs; It said they were "unauthorized". So I'm closing those PRs in favor of this one.

Making dependabot changes

---

docs/_source/docs/faq.rst
docs/_source/docs/templates.rst

This updates our docs to no longer reference the old CDK approach (which didn't work with CDK assets). In its place, it references the new `sceptre-cdk-handler` package that covers that functionality.

[Resolve #1264] Updating the CDK docs to point to the new sceptre-cdk-handler

---

.pre-commit-config.yaml
sceptre/config/reader.py
sceptre/connection_manager.py
tests/fixtures-vpc/templates/vpc_sud.py
tests/fixtures/templates/vpc_sud.py
tests/test_config_reader.py

Update pre-commit linter to fix pre-commit error:
```
An unexpected error has occurred: CalledProcessError: command: ('/home/circleci/.cache/pre-commit/repoen6j6mg_/py_env-python3/bin/python', '-mpip', 'install', '.')
```
Changes in this PR was generated from running the commands:
* `pre-commit autoupdate`
*  `pre-commit run --all-files`

update pre-commit linters

---

CHANGELOG.md
pyproject.toml

- [Resolve #1358] Updating PyYaml to ^6.0 (#1359)

Releasing v4.2.2

---

.pre-commit-config.yaml

Tox supports up to 3.11.
https://github.com/Sceptre/sceptre/blob/95d4a92b6e9fbb5a8f77a79e017016c0595f4bcb/tox.ini#L3

[Resolves #1370] Use Python 3.11 for Black

---

CONTRIBUTING.md

@jfalkenstein gave this guidance on the Slack channel.

Show how to build documentation

---

.circleci/config.yml
README.md

Twitter has been crap lately and the Automated announcements to twitter have been a PITA to maintain so we are removing it.

[Resolves #1377] Remove auto announcements to twitter

---

.github/main.yaml

Initial setup to kickstart the GH actions CI process. This will allow us to test follow on PRs for the
migration to GH actions.

bootstrap GH action CI

---

.github/workflows/main.yaml

ci: unit tests broken, attempt fix by running setup python step
before install poetry step.

ci: attempt unit test fix

---

.github/workflows/branch-integration-tests.yaml

We want to trigger integration tests on every branch except master branch. Got this from stackoverflow[1]
[1] https://stackoverflow.com/a/57903434

Fix integration test workflow

---

docs/_source/docs/stack_config.rst
docs/_source/docs/stack_group_config.rst
sceptre/config/reader.py
sceptre/config/strategies.py
tests/test_config_reader.py

Add configuration for inheritance strategies for list and dict configs.
This resolves #1187 by allowing selecting a dict_merge strategy at a stack group/stack level, while remaining backwards compatible with existing stacks by retaining the default of child_wins.
This does not however address the example from the original issue of including tags of dependencies (or dependents?), as I don't believe this fits with the existing model (or makes sense as a use case).
This PR additionally adds the same support to all list and dict based configs.
The config for inheritance strategy itself is also inheritable, but not configurable.
From the original issue example:
Example:
Assume Sceptre project A, B and C with dependency C -> B
root StackConfig config/config.yaml
```
stack_tags_inheritance: …
```

[Resolves #1187] Add configuration for inheritance strategies for list and dict configs

---

CONTRIBUTING.md

A minor clarification to the docs on running integration tests.

A minor clarification to the docs on running integration tests

---

pyproject.toml

[Resolves #841] Add documented name as entry point for ASG hook

---

CHANGELOG.md
pyproject.toml

Bump version and update changelog for release v4.5.0

Bump version and update changelog for release v4.5.0

---

CHANGELOG.md
pyproject.toml

Bump version and update changelog for release v4.5.1

Bump version and update changelog for release v4.5.1

---

CHANGELOG.md
pyproject.toml

Bump version and update changelog for release v4.5.2

Bump version and update changelog for release v4.5.2

---

.github/workflows/release.yaml

follow pattern from https://github.com/docker/metadata-action?tab=readme-ov-file#basic

Fix release failure with update to docker metadata action

---

.readthedocs.yaml

readthedocs build is failing https://app.readthedocs.org/projects/sceptre/

attempt to fix doc build on readthedocs
